var categories = {
  "si_prefixes": {
    "name": "SI Prefixes",
    "source": "http://en.wikipedia.org/wiki/Metric_prefix",
    "values": [
      "yotta",
      "zetta",
      "exa",
      "peta",
      "tera",
      "giga",
      "mega",
      "kilo",
      "hecto",
      "deca",
      "deci",
      "centi",
      "milli",
      "micro",
      "nano",
      "pico",
      "femto",
      "atto",
      "zepto",
      "yocto"
    ]
  },
  "si_units": {
    "name": "SI Units",
    "source": "http://en.wikipedia.org/wiki/Outline_of_the_metric_system",
    "values": [
      "Abampere",
      "Abcoulomb",
      "Abhenry",
      "Abohm",
      "Abvolt",
      "Ampere",
      "Apostilb",
      "Astronomical",
      "Dalton",
      "Barye",
      "Becquerel",
      "Bril",
      "Candela",
      "Celsius",
      "Centimetre",
      "Coulomb",
      "Cubic",
      "Curie",
      "Day",
      "Decibel",
      "Degree",
      "Dyne",
      "Electronvolt",
      "Erg",
      "Farad",
      "Gal",
      "Gauss",
      "Gram",
      "Grave",
      "Gray",
      "Hectare",
      "Henry",
      "Hertz",
      "Hour",
      "Joule",
      "Katal",
      "Kelvin",
      "Kilogram",
      "Litre",
      "Lumen",
      "Lux",
      "Maxwell",
      "Metre",
      "Microgram",
      "Minute",
      "Mole",
      "Neper",
      "Newton",
      "Oersted",
      "Ohm",
      "Pascal",
      "Phot",
      "Poise",
      "Radian",
      "Rayleigh",
      "Roentgen",
      "Second",
      "Siemens",
      "Sievert",
      "Skot",
      "Square",
      "Statcoulomb",
      "Statvolt",
      "Steradian",
      "Stilb",
      "Torr",
      "Stokes",
      "Tesla",
      "Tonne",
      "Volt",
      "Watt",
      "Weber"
    ]
  },
  "elements": {
    "name": "Chemical Elements",
    "source": "https://en.wikipedia.org/wiki/List_of_elements",
    "values": [
      "Hydrogen",
      "Helium",
      "Lithium",
      "Beryllium",
      "Boron",
      "Carbon",
      "Nitrogen",
      "Oxygen",
      "Fluorine",
      "Neon",
      "Sodium",
      "Magnesium",
      "Aluminium",
      "Silicon",
      "Phosphorus",
      "Sulfur",
      "Chlorine",
      "Argon",
      "Potassium",
      "Calcium",
      "Scandium",
      "Titanium",
      "Vanadium",
      "Chromium",
      "Manganese",
      "Iron",
      "Cobalt",
      "Nickel",
      "Copper",
      "Zinc",
      "Gallium",
      "Germanium",
      "Arsenic",
      "Selenium",
      "Bromine",
      "Krypton",
      "Rubidium",
      "Strontium",
      "Yttrium",
      "Zirconium",
      "Niobium",
      "Molybdenum",
      "Technetium",
      "Ruthenium",
      "Rhodium",
      "Palladium",
      "Silver",
      "Cadmium",
      "ndium",
      "Tin",
      "Antimony",
      "Tellurium",
      "odine",
      "Xenon",
      "Caesium",
      "Barium",
      "Lanthanum",
      "Cerium",
      "Praseodymiu",
      "Neodymium",
      "Promethium",
      "Samarium",
      "Europium",
      "Gadolinium",
      "Terbium",
      "Dysprosium",
      "Holmium",
      "Erbium",
      "Thulium",
      "Ytterbium",
      "Lutetium",
      "Hafnium",
      "Tantalum",
      "Tungsten",
      "Rhenium",
      "Osmium",
      "ridium",
      "Platinum",
      "Gold",
      "Mercury",
      "Thallium",
      "Lead",
      "Bismuth",
      "Polonium",
      "Astatine",
      "Radon",
      "Francium",
      "Radium",
      "Actinium",
      "Thorium",
      "Protactinium",
      "Uranium",
      "Neptunium",
      "Plutonium",
      "Americium",
      "Curium",
      "Berkelium",
      "Californium",
      "Einsteinium",
      "Fermium",
      "Mendelevium",
      "Nobelium",
      "Lawrencium",
      "Rutherfordium",
      "Dubnium",
      "Seaborgium",
      "Bohrium",
      "Hassium",
      "Meitnerium",
      "Darmstadtium",
      "Roentgenium",
      "Copernicium",
      "Ununtrium",
      "Flerovium",
      "Ununpentium",
      "Livermorium",
      "Ununseptium",
      "Ununoctium"
    ]
  },
  "colors": {
    "name": "Colors (Basic)",
    "source": "https://simple.wikipedia.org/wiki/List_of_colors",
    "values": [
      "Beige",
      "Black",
      "Blue",
      "Bronze",
      "Brown",
      "Cyan",
      "Golden",
      "Gray",
      "Green",
      "Lilac",
      "Magenta",
      "Mauve",
      "Olive",
      "Orange",
      "Pink",
      "Purple",
      "Red",
      "Rose",
      "Silver",
      "Violet",
      "White",
      "Yellow"
    ]
  },
  "colors_extended": {
    "name": "Colors (Extended)",
    "source": "https://simple.wikipedia.org/wiki/List_of_colors",
    "values": [
      "Amaranth",
      "Amber",
      "Amethyst",
      "Apricot",
      "Aquamarine",
      "Azure",
      "Baby blue",
      "Beige",
      "Black",
      "Blue",
      "Blue-green",
      "Blue-violet",
      "Blush",
      "Bronze",
      "Brown",
      "Burgundy",
      "Byzantium",
      "Carmine",
      "Cerise",
      "Cerulean",
      "Champagne",
      "Chartreuse green",
      "Chocolate",
      "Cobalt blue",
      "Coffee",
      "Copper",
      "Coral",
      "Crimson",
      "Cyan",
      "Desert sand",
      "Electric blue",
      "Emerald",
      "Erin",
      "Gold",
      "Gray",
      "Green",
      "Harlequin",
      "Indigo",
      "Ivory",
      "Jade",
      "Jungle green",
      "Lavender",
      "Lemon",
      "Lilac",
      "Lime",
      "Magenta",
      "Magenta rose",
      "Maroon",
      "Mauve",
      "Navy blue",
      "Ocher",
      "Olive",
      "Orange",
      "Orange-red",
      "Orchid",
      "Peach",
      "Pear",
      "Periwinkle",
      "Persian blue",
      "Pink",
      "Plum",
      "Prussian blue",
      "Puce",
      "Purple",
      "Raspberry",
      "Red",
      "Red-violet",
      "Rose",
      "Ruby",
      "Salmon",
      "Sangria",
      "Sapphire",
      "Scarlet",
      "Silver",
      "Slate gray",
      "Spring bud",
      "Spring green",
      "Tan",
      "Taupe",
      "Teal",
      "Turquoise",
      "Violet",
      "Viridian",
      "White",
      "Yellow"
    ]
  },
  "us_state_flowers": {
    "name": "US State Flowers",
    "source": "http://en.wikipedia.org/wiki/List_of_U.S._state_flowers",
    "values": [
      "Camellia",
      "Oak-leaf hydrangea",
      "Forget-me-not",
      "Saguaro cactus blossom",
      "Apple blossom",
      "California poppy",
      "Columbine",
      "Mountain laurel",
      "Peach blossom",
      "Orange blossom",
      "Tickseed",
      "Cherokee Rose",
      "Azalea",
      "Hawaiian hibiscus",
      "Syringa",
      "Mock Orange",
      "Violet",
      "Peony",
      "Wild Prairie Rose",
      "Sunflower",
      "Goldenrod",
      "Magnolia",
      "Louisiana Iris",
      "Black-eyed susan",
      "Mayflower",
      "Apple blossom",
      "Dwarf Lake Iris",
      "Magnolia",
      "Tickseed",
      "Hawthorn",
      "Bitterroot",
      "Goldenrod",
      "Sagebrush",
      "Purple lilac",
      "Violet",
      "Yucca flower",
      "Rose",
      "Flowering Dogwood",
      "Wild Prairie Rose",
      "Scarlet Carnation",
      "Large white trillium",
      "Oklahoma Rose",
      "Mistletoe",
      "Indian Blanket",
      "Oregon grape",
      "Mountain Laurel",
      "Penngift Crown Vetch",
      "Violet",
      "Yellow Jessamine",
      "Goldenrod",
      "Pasque flower",
      "Iris",
      "Purple Passionflower",
      "Bluebonnet",
      "Sego lily",
      "Red Clover",
      "American Dogwood",
      "Coast Rhododendron",
      "Rhododendron",
      "Wood Violet"
    ]
  },
  "common_asians_names": {
    "name": "Common Asian Names",
    "source": "http://en.wikipedia.org/wiki/List_of_common_Chinese_surnames",
    "values": [
      "Lee",
      "Chen",
      "Wong",
      "Yang",
      "Wang",
      "Chang",
      "Chan",
      "Li",
      "Lin",
      "Liu",
      "Tan",
      "Lim",
      "Ng",
      "Ong",
      "Goh",
      "Chua",
      "Koh",
      "Teo",
      "Zhang",
      "Lam",
      "Leung",
      "Ho"
    ]
  },
  "impressive_chemistry": {
    "name": "Impressive Chemical Names",
    "source": "http://chemistry.about.com/od/chemicaldatabases/a/Chemical-Names-Of-Common-Substances.htm",
    "values": [
      "keton",
      "bisulfate",
      "acid",
      "hydroxide",
      "alcohol",
      "disulfide",
      "potassium",
      "oxide",
      "thiosulfate",
      "glycol",
      "trisulfide",
      "trioxide",
      "oxysulfide",
      "solution",
      "silicate",
      "bicarbonate",
      "acetate",
      "sulfate",
      "hydrogen",
      "chloride",
      "dichromate",
      "lim",
      "sulfat",
      "borat",
      "copper",
      "trichloride",
      "stanni",
      "chlorid",
      "dioxide",
      "carbonate",
      "nitrate",
      "hypochlorite",
      "bitartrate",
      "thiophosphate",
      "crystal ",
      "ferricyanide",
      "formaldehyd",
      "linseed",
      "cynanide",
      "thiosulfat",
      "hydroxid",
      "monoxide",
      "potash",
      "salicylate",
      "ferrocyanide",
      "acetoarsenite",
      "cyanide",
      "pyrophosphate",
      "tetraoxide",
      "acetat",
      "binoxalate",
      "dilut"
    ]
  },
  "fish": {
    "name": "Fish and Shellfish",
    "source": "http://www.schmidtzeevis.nl/html/fish_names_in_7_languages.html",
    "values": [
      "Anchovy",
      "Perch",
      "Flounder",
      "Trout",
      "Garfish",
      "Gilt Head Bream",
      "Brill",
      "Coding",
      "Shark",
      "Mullet",
      "Herring",
      "Hake",
      "Halibut",
      "Horse Mackerel",
      "Octopus",
      "Squid",
      "Cuttlefish",
      "Cod",
      "Carp",
      "Caviar",
      "Saithe",
      "Frostfish",
      "Ling",
      "Capelin",
      "Mackerel",
      "Marlin",
      "Catfisch",
      "Goatfish",
      "Moray",
      "Croaker",
      "Drum",
      "Meagre",
      "Joey",
      "Eel",
      "Parrot fish",
      "Sardinella",
      "Weever",
      "Pilchard",
      "Plaice",
      "Tub gurnard",
      "Gurnard",
      "Eelpout",
      "Ray",
      "Skate",
      "Red Bream",
      "Sailfish",
      "Brisling",
      "Dab",
      "Haddock",
      "Scorpionfish",
      "Sandeel",
      "Pike",
      "Pike-perch",
      "Smelt",
      "Sprat",
      "Pout",
      "Sturgeon",
      "Stockfish",
      "John Dory",
      "Turbot",
      "Sole",
      "Tuna",
      "Bonito",
      "Filefish",
      "Triggerfish",
      "Pollack",
      "Flying Fish",
      "Whiting",
      "Silver hake",
      "Salmon",
      "Sea Bass",
      "Grouper",
      "Sea Bream",
      "Anglerfish",
      "Tench",
      "Conger",
      "Catfish",
      "Shrimp",
      "Crab",
      "Lobster",
      "Crawfish",
      "Periwinkle",
      "Scallop",
      "Cockle",
      "Mussel",
      "Oyster",
      "Razor shell",
      "clam",
      "Carpet Shell",
      "Hard Clam",
      "Whelk"
    ]
  },
  "endangered_species": {
    "name": "Endangered Species",
    "source": "http://worldwildlife.org/species/directory?sort=extinction_status&direction=desc",
    "values": [
      "Amur Leopard",
      "Black Rhino",
      "Cross River Gorilla",
      "Hawksbill Turtle",
      "Javan Rhino",
      "Leatherback Turtle",
      "Mountain Gorilla",
      "Saola",
      "South China Tiger",
      "Sumatran Elephant",
      "Sumatran Orangutan",
      "Sumatran Rhino",
      "Sumatran Tiger",
      "Sumatran",
      "Vaquita",
      "Western Lowland Gorilla",
      "Yangtze Finless Porpoise",
      "African Wild Dog",
      "Amur Tiger",
      "Asian Elephant",
      "Bengal Tiger",
      "Black Spider Monkey",
      "Black-footed Ferret",
      "Blue Whale",
      "Bluefin Tuna",
      "Bonobo",
      "Bornean Orangutan",
      "Borneo Pygmy Elephant",
      "Chimpanzee",
      "Eastern Lowland Gorilla",
      "Fin Whale",
      "Galápagos Penguin",
      "Ganges River Dolphin",
      "Giant Panda",
      "Green Turtle",
      "Hector's Dolphin",
      "Humphead Wrasse",
      "Indian Elephant",
      "Indochinese Tiger",
      "Indus River Dolphin",
      "Loggerhead Turtle",
      "Malayan Tiger",
      "North Atlantic Right Whale",
      "Orangutan",
      "Sea Lions",
      "Sei Whale",
      "Snow Leopard",
      "Sri Lankan Elephant",
      "Tiger",
      "Whale",
      "African Elephant",
      "Bigeye Tuna",
      "Dugong",
      "Forest Elephant",
      "Giant Tortoise",
      "Great White Shark",
      "Greater One Horned Rhino",
      "Irrawaddy Dolphin",
      "Marine Iguana",
      "Olive Ridley Turtle",
      "Polar Bear",
      "Red Panda",
      "Savanna Elephant",
      "Southern rockhopper penguin",
      "Whale Shark",
      "Albacore Tuna",
      "Beluga",
      "Greater Sage-Grouse",
      "Jaguar",
      "Monarch Butterfly",
      "Mountain Plover",
      "Narwhal",
      "Plains Bison",
      "White Rhino",
      "Yellowfin Tuna",
      "Arctic Fox",
      "Arctic Wolf",
      "Bowhead Whale",
      "Brown Bear",
      "Gray Whale",
      "Macaw",
      "Pronghorn",
      "Skipjack Tuna",
      "Amazon River Dolphin",
      "Dolphins and Porpoises",
      "Elephant",
      "Gorilla",
      "Pacific Salmon",
      "Penguin",
      "Poison Dart Frog",
      "Rhino",
      "Sea Turtle",
      "Seals",
      "Shark",
      "Tree Kangaroo",
      "Tuna"
    ]
  },
  "squamata": {
    "name": "Scaled Reptiles Families",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427e7mnphgro3c",
    "values": [
      "Agamidae",
      "Amphisbaenia",
      "Amphisbaenidae",
      "Anguidae",
      "Anniellidae",
      "Chamaeleonidae",
      "Cordylidae",
      "Corytophanidae",
      "Crotaphytidae",
      "Dibamidae",
      "Gekkonidae",
      "Gerrhosauridae",
      "Gymnophthalmidae",
      "Helodermatidae",
      "Hoplocercidae",
      "Hydrophiidae",
      "Iguanidae",
      "Lacertidae",
      "Lanthanotidae",
      "Opluridae",
      "Phrynosomatidae",
      "Polychrotidae",
      "Pygopodidae",
      "Rhineuridae",
      "Scincidae",
      "Teiidae",
      "Tropiduridae",
      "Varanidae",
      "Xantusiidae",
      "Xenosauridae",
      "Henophidia",
      "Xenophidia"
    ]
  },
  "us_copycats_counties": {
    "name": "Some US Counties",
    "source": "http://en.wikipedia.org/wiki/List_of_U.S._counties_named_after_other_U.S._counties",
    "values": [
      "Albany",
      "Champaign",
      "Christian",
      "Genesee",
      "Hardin",
      "Henderson",
      "Lancaster",
      "Lincoln",
      "Mason",
      "Oneida",
      "Orange",
      "Otsego",
      "Richland",
      "Williamson",
      "Woodford",
      "York"
    ]
  },
  "national_capitals": {
    "name": "National Capitals",
    "source": "http://en.wikipedia.org/wiki/List_of_national_capitals_in_alphabetical_order",
    "values": [
      "Abu Dhabi",
      "Abuja",
      "Accra",
      "Adamstown",
      "Addis Ababa",
      "Algiers",
      "Alofi",
      "Amman",
      "Amsterdam",
      "Andorra la Vella",
      "Ankara",
      "Antananarivo",
      "Apia",
      "Ashgabat",
      "Asmara",
      "Astana",
      "Asunción",
      "Athens",
      "Avarua",
      "Baghdad",
      "Baku",
      "Bamako",
      "Bandar Seri Begawan",
      "Bangkok",
      "Bangui",
      "Banjul",
      "Basseterre",
      "Beijing",
      "Beirut",
      "Belgrade",
      "Belmopan",
      "Berlin",
      "Bern",
      "Bishkek",
      "Bissau",
      "Bogotá",
      "Brasília",
      "Bratislava",
      "Brazzaville",
      "Bridgetown",
      "Brussels",
      "Bucharest",
      "Budapest",
      "Buenos Aires",
      "Bujumbura",
      "Cairo",
      "Canberra",
      "Caracas",
      "Castries",
      "Cayenne",
      "Charlotte Amalie",
      "Chisinau",
      "Cockburn Town",
      "Conakry",
      "Copenhagen",
      "Dakar",
      "Damascus",
      "Dhaka",
      "Dili",
      "Djibouti",
      "Doha",
      "Douglas",
      "Dublin",
      "Dushanbe",
      "Edinburgh of the Seven Seas",
      "El Aaiún",
      "Episkopi Cantonment",
      "Flying Fish Cove",
      "Freetown",
      "Funafuti",
      "Gaborone",
      "George Town",
      "Georgetown",
      "Georgetown",
      "Gibraltar",
      "Grytviken",
      "Guatemala City",
      "Gustavia",
      "Hagåtña",
      "Hamilton",
      "Hanga Roa",
      "Hanoi",
      "Harare",
      "Hargeisa",
      "Havana",
      "Helsinki",
      "Honiara",
      "Islamabad",
      "Jakarta",
      "Jamestown",
      "Jerusalem",
      "Ramallah and Gaza",
      "Juba",
      "Kabul",
      "Kampala",
      "Kathmandu",
      "Khartoum",
      "Kiev",
      "Kigali",
      "Kingston",
      "Kingston",
      "Kingstown",
      "Kinshasa",
      "Kuala Lumpur",
      "Putrajaya",
      "Kuwait City",
      "Libreville",
      "Lilongwe",
      "Lima[h]",
      "Lisbon",
      "Ljubljana",
      "Lomé",
      "London",
      "Luanda",
      "Lusaka",
      "Luxembourg",
      "Madrid",
      "Majuro",
      "Malabo",
      "Malé",
      "Managua",
      "Manama",
      "Manila",
      "Maputo",
      "Marigot",
      "Maseru",
      "Mata-Utu",
      "Mbabane",
      "Lobamba",
      "Melekeok",
      "Ngerulmud",
      "Mexico City",
      "Minsk",
      "Mogadishu",
      "Monaco",
      "Monrovia",
      "Montevideo",
      "Moroni",
      "Moscow",
      "Muscat",
      "Nairobi",
      "Nassau",
      "Naypyidaw",
      "N'Djamena",
      "New Delhi",
      "Niamey",
      "Nicosia",
      "Nicosia",
      "Nouakchott",
      "Nouméa",
      "Nukuʻalofa",
      "Nuuk",
      "Oranjestad",
      "Oslo",
      "Ottawa",
      "Ouagadougou",
      "Pago Pago",
      "Palikir",
      "Panama City",
      "Papeete",
      "Paramaribo",
      "Paris",
      "Philipsburg",
      "Phnom Penh",
      "Plymouth",
      "Brades Estate",
      "Podgorica",
      "Cetinje",
      "Port Louis",
      "Port Moresby",
      "Port Vila",
      "Port-au-Prince",
      "Port of Spain",
      "Porto-Novo",
      "Cotonou",
      "Prague",
      "Praia",
      "Pretoria",
      "Bloemfontein",
      "Cape Town",
      "Pristina",
      "Pyongyang",
      "Quito",
      "Rabat",
      "Reykjavík",
      "Riga",
      "Riyadh",
      "Road Town",
      "Rome",
      "Roseau",
      "Saipan",
      "San José",
      "San Juan",
      "San Marino",
      "San Salvador",
      "Sana'a",
      "Santiago",
      "Valparaíso",
      "Santo Domingo",
      "São Tomé",
      "Sarajevo",
      "Seoul",
      "Singapore",
      "Skopje",
      "Sofia",
      "Colombo",
      "St. George's",
      "St. Helier",
      "St. John's",
      "St. Peter Port",
      "St. Pierre",
      "Stanley",
      "Stepanakert",
      "Stockholm",
      "Sucre",
      "La Paz",
      "Sukhumi",
      "Suva",
      "Taipei",
      "Tallinn",
      "Tarawa",
      "Tashkent",
      "Tbilisi",
      "Kutaisi",
      "Tegucigalpa",
      "Tehran",
      "Thimphu",
      "Tirana",
      "Tiraspol",
      "Tokyo",
      "Tórshavn",
      "Tripoli",
      "Tskhinvali",
      "Tunis",
      "Ulan Bator",
      "Vaduz",
      "Valletta",
      "The Valley",
      "Vatican City",
      "Victoria",
      "Vienna",
      "Vientiane",
      "Vilnius",
      "Warsaw",
      "Washington",
      "Wellington",
      "West Island",
      "Willemstad",
      "Windhoek",
      "Abidjan",
      "Yaoundé",
      "Yaren",
      "Yerevan",
      "Zagreb"
    ]
  },
  "cats": {
    "name": "Cats",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427emme6ununpd",
    "values": [
      "Chausie",
      "British Longhair",
      "Maine Coon",
      "Bengal",
      "York Chocolate",
      "Ragdoll",
      "Highlander",
      "Siberian",
      "Ragamuffin",
      "Norwegian Forest Cat",
      "Pixie‐Bob",
      "California Spangled Cat",
      "British Shorthair",
      "Turkish Van",
      "Birman",
      "Australian Mist",
      "Chartreux",
      "Burmilla",
      "Abyssinian",
      "European Shorthair",
      "Oriental Longhair",
      "American Shorthair",
      "Himalayan",
      "Persian",
      "American Wirehair",
      "Sphynx",
      "Tiffanie",
      "Sokoke",
      "American Bobtail",
      "German Rex",
      "Exotic Shorthair",
      "Chinese Li Hua Mao",
      "Burmese",
      "European Burmese",
      "Oriental Shorthair",
      "Ocicat",
      "Kurilian Bobtail",
      "Cymric",
      "Manx",
      "Scottish Fold",
      "LaPerm",
      "Somali",
      "Siamese Traditional",
      "Toyger",
      "Ojos Azules",
      "Donskoy",
      "Serengeti",
      "Siamese Modern",
      "Tonkinese",
      "Snowshoe",
      "Selkirk Rex",
      "Chantilly",
      "Bombay",
      "American Curl",
      "Peterbald",
      "Russian Blue",
      "Javanese",
      "Turkish Angora",
      "Balinese",
      "Korats",
      "Havana Brown",
      "Nebelung",
      "Egyptian Mau",
      "Cornish Rex",
      "Minskin",
      "Munchkin",
      "Japanese Bobtail",
      "Devon Rex",
      "Colorpoint Shorthair",
      "Singapura"
    ]
  },
  "jazz_first": {
    "name": "Jazz Firstnames",
    "source": "https://en.wikipedia.org/wiki/List_of_jazz_musicians",
    "values": [
      "Scott",
      "Charles",
      "Duke",
      "Louis",
      "Joe",
      "Earl",
      "Fats",
      "Count",
      "Stephane",
      "Benny",
      "Art",
      "Sun",
      "Ward",
      "Thelonious",
      "Dizzy",
      "Clark",
      "Charlie",
      "Dave",
      "Charles",
      "Oscar",
      "Miles",
      "John",
      "Gerry",
      "Chet",
      "Ornette",
      "Wynton"
    ]
  },
  "jazz_last": {
    "name": "Jazz Lastnames",
    "source": "https://en.wikipedia.org/wiki/List_of_jazz_musicians",
    "values": [
      "Joplin",
      "Bolden",
      "Ellington",
      "Armstrong",
      "Venuti",
      "Hines",
      "Waller",
      "Basie",
      "Grappelli",
      "Goodman",
      "Tatum",
      "Ra",
      "Kimball",
      "Monk",
      "Gillespie",
      "Terry",
      "Parker",
      "Brubeck",
      "Mingus",
      "Peterson",
      "Davis",
      "Coltrane",
      "Mulligan",
      "Baker",
      "Coleman",
      "Marsalis"
    ]
  },
  "blues_names": {
    "name": "Blues Nicknames",
    "source": "http://www.outliermusic.com/jokes_bluesname.htm",
    "values": [
      "Bones",
      "Money",
      "Harp",
      "Legs",
      "Eyes",
      "Lemon",
      "Killer",
      "Hips",
      "Lips",
      "Fingers",
      "Boy",
      "Liver",
      "Gumbo",
      "Foot",
      "Mama",
      "Back",
      "Duke",
      "Dog",
      "Bad Boy",
      "Baby",
      "Chicken",
      "Pickles",
      "Sugar",
      "Cracker",
      "Tooth",
      "Smoke ",
      "Huh",
      "Fat",
      "Muddy",
      "Crippled",
      "Old",
      "Texas",
      "Hollerin'",
      "Ugly",
      "Brown",
      "Happy",
      "Boney",
      "Curly",
      "Pretty",
      "Jailhouse",
      "Peg Leg",
      "Red",
      "Sleepy",
      "Bald",
      "Skinny",
      "Blind",
      "Big",
      "Yella",
      "Toothless",
      "Screamin'",
      "Fat Boy",
      "Washboard",
      "Steel-Eye",
      "Jackson",
      "McGee",
      "Hopkins",
      "Dupree",
      "Green",
      "Jones",
      "Rivers",
      "Malone",
      "Washington",
      "Smith",
      "Parker",
      "Lee",
      "Thompkins",
      "King",
      "Bradley",
      "Hawkins",
      "Jefferson",
      "Davis",
      "Franklin",
      "White",
      "Jenkins",
      "Bailey",
      "Johnson",
      "Blue",
      "Allison",
      "Huh"
    ]
  },
  "flowers": {
    "name": "Flowers",
    "source": "http://www.whatiscalled.com/flower-names-in-all-languages/",
    "values": [
      "Arabian Jasmine",
      "Lily",
      "Buttercups",
      "China Rose",
      "Cobra Saffron",
      "Crossandra",
      "Cypress Vine",
      "Daffodils",
      "Dahlia",
      "Daisy",
      "Damask Rose",
      "Datura",
      "Creeper",
      "Jasmine",
      "Four O'clock",
      "Frangipani",
      "Gallant Soldier",
      "Galinsoga Parviflora",
      "Globe Amaranth",
      "Golden Champa",
      "Indian Tulip",
      "Ixora",
      "Kewda",
      "Kurinji",
      "Violet",
      "Lotus",
      "Maloo Creeper",
      "Maulsari",
      "Midday Flower",
      "Oleander",
      "Peacock Flower",
      "Periwinkle",
      "Myrtle",
      "Rose",
      "Star Jasmine",
      "Sunflower",
      "Cassia",
      "Tulips",
      "Water Lily",
      "Bougainvillea",
      "Zinnia",
      "Ceylon Ironwood",
      "Bullet Wood",
      "Chrysanthemum",
      "Cockscomb",
      "Amaranth",
      "Pine",
      "Ghanera",
      "Hiptage",
      "Hummingbird Vine",
      "Chestnut",
      "Jungle Flame",
      "Pink Jasmine",
      "Star Glory",
      "Superb Lily",
      "Artichoke",
      "Chamomile",
      "Cannabis",
      "Citrus",
      "Blossoms",
      "Clover",
      "Dandelions",
      "Daylily",
      "Elderflower",
      "Hibiscus",
      "Honeysuckle",
      "Nasturtium",
      "Sweet",
      "Osmanthus",
      "Pansy",
      "Calendula",
      "Officinalis",
      "Sesbania",
      "Grandiflora",
      "Zucchini",
      "Aurantiaca",
      "Alba"
    ]
  },
  "animals": {
    "name": "Animals",
    "source": "http://tamilcube.com/res/indian_animals.html",
    "values": [
      "Ant",
      "Bear",
      "Buffalo",
      "Butterfly",
      "Camel",
      "Cat",
      "Chameleon",
      "Chimpanzee",
      "Cow",
      "Crocodile",
      "Crab",
      "Deer",
      "Dog",
      "Donkey",
      "Elephant",
      "Fox",
      "Frog",
      "Goat",
      "Gorilla",
      "Horse",
      "Hippopotamus",
      "Jackal",
      "Lion",
      "Lizard",
      "Mongoose",
      "Monkey",
      "mosquito",
      "Mouse",
      "Ox",
      "Pig",
      "Polar Bear",
      "Rabbit",
      "Rat",
      "Rhinoceros",
      "Sheep",
      "Snail",
      "Snake",
      "Spider",
      "Squirrel",
      "Tiger",
      "Turtle",
      "Wolf"
    ]
  },
  "imperial": {
    "name": "Imperial Units",
    "source": "http://wiki.answers.com/Q/List_of_imperial_units",
    "values": [
      "pound",
      "ounce",
      "thou",
      "inch",
      "foot",
      "yard",
      "chain",
      "furlong",
      "mile",
      "league",
      "fathom",
      "cable",
      "nautical",
      "link",
      "rod",
      "perch",
      "rood",
      "acre",
      "gill",
      "pint",
      "quart",
      "gallon",
      "minim",
      "scruple",
      "drachm",
      "grain",
      "stone",
      "quarter",
      "hundredweight",
      "ton"
    ]
  },
  "california_cities": {
    "name": "Californian Cities",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427eue1f1uq3b4",
    "values": [
      "Bakersfield",
      "Anaheim",
      "Santa Ana",
      "Riverside",
      "Stockton",
      "ChuVista",
      "Fremont",
      "Irvine",
      "Modesto",
      "Oxnard",
      "Fontana",
      "Moreno",
      "Glendale",
      "Huntington",
      "Clarita",
      "Rosa",
      "Oceanside",
      "Cucamonga",
      "Ontario",
      "Lancaster",
      "Elk Grove",
      "Palmdale",
      "Corona",
      "Salinas",
      "Pomona",
      "Torrance",
      "Hayward",
      "Escondido",
      "Sunnyvale",
      "Pasadena",
      "Orange",
      "Fullerton",
      "Visalia",
      "Valley",
      "Concord",
      "Roseville",
      "Clara",
      "Vallejo",
      "Victorville",
      "Monte",
      "Berkeley",
      "Downey",
      "Mesa",
      "Inglewood",
      "Covina",
      "Norwalk",
      "Carlsbad",
      "Fairfield",
      "Richmond",
      "Murrieta",
      "Burbank",
      "Antioch",
      "Daly",
      "Temecula",
      "Maria",
      "Cajon",
      "Rialto",
      "Mateo",
      "Compton",
      "Clovis",
      "Gate",
      "Vista",
      "Viejo",
      "Vacaville",
      "Arden",
      "Carson",
      "Hesperia",
      "Redding",
      "Monica",
      "Westminster",
      "Barbara",
      "Chico",
      "Whittier",
      "Newport",
      "Leandro",
      "Hawthorne",
      "Marcos",
      "Citrus",
      "Alhambra",
      "Tracy",
      "Livermore",
      "Buena",
      "Lakewood",
      "Merced",
      "Hemet",
      "Chino",
      "Napa",
      "Redwood",
      "Bellflower",
      "Indio",
      "Tustin",
      "Baldwin",
      "Chino",
      "Mountain View",
      "Alameda",
      "Upland",
      "Folsom",
      "Ramon",
      "Pleasanton",
      "Lynwood",
      "Union",
      "Redlands",
      "Turlock",
      "Perris",
      "Manteca",
      "Milpitas",
      "Redondo",
      "Davis",
      "Camarillo",
      "Yuba",
      "Cordova",
      "Palo Alto",
      "Yorba Linda",
      "Walnut Creek",
      "Clemente",
      "Florence-Graham",
      "Pittsburg",
      "Laguna Niguel",
      "Pico Rivera",
      "Montebello",
      "Lodi",
      "Carmichael",
      "Madera",
      "Castro",
      "Monterey",
      "Habra",
      "Santa Cruz",
      "Encinitas",
      "Tulare",
      "Gardena",
      "Cupertino",
      "Huntington",
      "Petaluma",
      "Rafael",
      "Whittier",
      "Mesa",
      "Rocklin",
      "Arcadia",
      "Diamond",
      "Woodland",
      "Fountain",
      "Porterville",
      "Paramount",
      "Hacienda",
      "Hanford",
      "Rosemead",
      "Santee",
      "Highland",
      "Delano",
      "Colton",
      "Novato",
      "Elsinore",
      "Brentwood",
      "Yucaipa",
      "Cathedral",
      "Watsonville",
      "Placentia",
      "Glendora"
    ]
  },
  "metals": {
    "name": "Metals",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427e48dr7di6c2",
    "values": [
      "lithium",
      "beryllium",
      "sodium",
      "magnesium",
      "aluminum",
      "potassium",
      "calcium",
      "scandium",
      "titanium",
      "vanadium",
      "chromium",
      "manganese",
      "iron",
      "cobalt",
      "nickel",
      "copper",
      "zinc",
      "gallium",
      "arsenic",
      "rubidium",
      "strontium",
      "yttrium",
      "zirconium",
      "niobium",
      "molybdenum",
      "technetium",
      "ruthenium",
      "rhodium",
      "palladium",
      "silver",
      "cadmium",
      "indium",
      "tin",
      "antimony",
      "cesium",
      "barium",
      "lanthanum",
      "cerium",
      "praseodymium",
      "neodymium",
      "promethium",
      "samarium",
      "europium",
      "gadolinium",
      "terbium",
      "dysprosium",
      "holmium",
      "erbium",
      "thulium",
      "ytterbium",
      "lutetium",
      "hafnium",
      "tantalum",
      "tungsten",
      "rhenium",
      "osmium",
      "iridium",
      "platinum",
      "gold",
      "mercury",
      "thallium",
      "lead",
      "bismuth",
      "polonium",
      "francium",
      "radium",
      "actinium",
      "thorium",
      "protactinium",
      "uranium",
      "neptunium",
      "plutonium",
      "americium",
      "curium",
      "berkelium",
      "californium",
      "einsteinium",
      "fermium",
      "mendelevium",
      "nobelium",
      "lawrencium",
      "rutherfordium",
      "dubnium",
      "seaborgium",
      "bohrium",
      "hassium",
      "meitnerium",
      "darmstadtium",
      "roentgenium",
      "copernicium",
      "ununtrium",
      "flerovium",
      "ununpentium",
      "livermorium"
    ]
  },
  "dogs": {
    "name": "Dog Breeds",
    "source": "https://en.wikipedia.org/wiki/List_of_most_popular_dog_breeds",
    "values": [
      "Labrador",
      "Retriever",
      "Cocker Spaniel",
      "Springer Spaniel",
      "German Shepherd",
      "Bull Terrier",
      "Spaniel",
      "Golden Retriever",
      "White Terrier",
      "Boxer",
      "Border Terrier",
      "Rottweiler",
      "Shih Tzu",
      "Miniature Schnauzer",
      "Lhasa Apso",
      "Yorkshire Terrier",
      "Bulldog",
      "Dobermann Pinscher",
      "Weimaraner",
      "Pug",
      "Whippet",
      "Bichon Frise",
      "Border Collie",
      "Siberian Husky",
      "Shar-Pei",
      "Dalmatian",
      "Great Dane",
      "Cairn Terrier",
      "Beagle",
      "Dachshund",
      "Poodle",
      "Chihuahua",
      "Pomeranian",
      "Boston Terrier",
      "Maltese",
      "Shorthaired Pointer",
      "Shetland Sheepdog",
      "Doberman Pinscher",
      "Welsh Corgi",
      "Miniature Pinscher",
      "Basset Hound"
    ]
  },
  "animal_babies": {
    "name": "Animal Babies",
    "source": "https://en.wikipedia.org/wiki/List_of_animal_names",
    "values": [
      "cub",
      "chick",
      "hatchling",
      "cria",
      "larva",
      "pupa",
      "pup",
      "calf",
      "infant",
      "baby",
      "foal",
      "kit",
      "kitten",
      "piglet",
      "farrow",
      "shoat",
      "shote",
      "caterpillar",
      "chrysalis",
      "nymph",
      "codling",
      "sprat",
      "shaglet",
      "whelp",
      "colt",
      "fawn",
      "juvenile",
      "puppy",
      "duckling",
      "eaglet",
      "fledgling",
      "puggle",
      "leptocephalus",
      "elver",
      "eyass",
      "eyas",
      "fry",
      "fingerling",
      "maggot",
      "polliwog",
      "tadpole",
      "froglet",
      "kid",
      "gosling",
      "chulengo",
      "keet",
      "leveret",
      "hoglet",
      "larvae",
      "pupae",
      "filly",
      "gelding",
      "child",
      "girl",
      "boy",
      "planula",
      "polyp",
      "ephyra",
      "joey",
      "pinky",
      "fuzzy",
      "crawler",
      "hopper",
      "wriggler",
      "tumbler",
      "eft",
      "owlet",
      "spat",
      "peachick",
      "nestling",
      "barrow",
      "gilt",
      "squab",
      "squeaker",
      "bunny",
      "lamb",
      "salamanderling",
      "seafoal",
      "lambkin",
      "cosset",
      "shrewlet",
      "snakelet",
      "neonate",
      "spiderling",
      "cygnet",
      "flapper",
      "toadlet",
      "poult",
      "wormlet"
    ]
  },
  "kingdom_animalia": {
    "name": "Kingdom Animalia",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427ekhnrbufb4a",
    "values": [
      "Acanthocephala",
      "Annelida",
      "Arthropoda",
      "Brachiopoda",
      "Cephalorhyncha",
      "Chaetognatha",
      "Cnidaria",
      "Ctenophora",
      "Cycliophora",
      "Echinodermata",
      "Echiura",
      "Ectoprocta",
      "Entoprocta",
      "Gastrotricha",
      "Gnathostomulida",
      "Hemichordata",
      "Mesozoa",
      "Mollusca",
      "Myxozoa",
      "Nemata",
      "Nemertea",
      "Phoronida",
      "Placozoa",
      "Platyhelminthes",
      "Porifera",
      "Rotifera",
      "Sipuncula",
      "Tardigrada"
    ]
  },
  "greek_gods": {
    "name": "Greek Gods",
    "source": "https://simple.wikipedia.org/wiki/List_of_Greek_gods_and_goddesses",
    "values": [
      "Chaos",
      "Erebus",
      "Gaia",
      "Nyx",
      "Tartarus",
      "Ouranos",
      "Thesis",
      "Phanes",
      "Anemois",
      "Boreas",
      "Kaikias",
      "Apeliotes",
      "Euros",
      "Notos",
      "Lips",
      "Zephyrus",
      "Skirion",
      "Hemera",
      "Zeus",
      "Hades",
      "Poseidon",
      "Hera",
      "Dementer",
      "Hestia",
      "Aphrodite",
      "Apollo",
      "Ares",
      "Artemis",
      "Athena",
      "Demeter",
      "Dionysus",
      "Hephaestus",
      "Hermes"
    ]
  },
  "greek_titans": {
    "name": "Greek Titans",
    "source": "https://simple.wikipedia.org/wiki/List_of_Greek_gods_and_goddesses",
    "values": [
      "Koios",
      "Kreios",
      "Kronos",
      "Hyperion",
      "Iapetos",
      "Mnemosyne",
      "Oceanus",
      "Phoebe",
      "Rhea",
      "Tethys",
      "Theia",
      "Themis",
      "Atlas",
      "Epimetheus",
      "Menoitios",
      "Prometheus",
      "Asteria",
      "Perses",
      "Asterious",
      "Dione"
    ]
  },
  "us_submarines": {
    "name": "US Submarine Classes",
    "source": "https://en.wikipedia.org/wiki/List_of_submarine_classes_of_the_United_States_Navy",
    "values": [
      "Alligator",
      "Holland",
      "Plunger",
      "Barracuda",
      "Argonaut",
      "Narwhal",
      "Dolphin",
      "Cachalot",
      "Porpoise",
      "Salmon",
      "Sargo",
      "Tambor",
      "Mackerel",
      "Gato",
      "Balao",
      "Tench",
      "Barracuda",
      "Tang",
      "Albacore",
      "Nautilus",
      "Sailfish",
      "Grayback",
      "Seawolf",
      "Darter",
      "Skate",
      "Barbel",
      "Skipjack",
      "Triton",
      "Halibut",
      "Thresher",
      "Permit",
      "Tullibee",
      "Lafayette",
      "Dolphin",
      "Sturgeon",
      "Narwhal",
      "Ohio",
      "Seawolf",
      "Virginia"
    ]
  },
  "german_words": {
    "name": "German Words",
    "source": "http://pascalhertleif.de/",
    "values": [
      "Vogel",
      "Topf",
      "Mond",
      "Nacht",
      "Mondschein",
      "Sanft",
      "Hast",
      "Teil",
      "Sonne",
      "Leben",
      "Aus",
      "Feuer",
      "Reise",
      "Morgenstern",
      "Asche",
      "Engel",
      "Herz",
      "Rosenrot",
      "Wahrheit",
      "Flammen",
      "Regen",
      "Wort",
      "Geheimnis",
      "Kraft",
      "Preis",
      "Wirklich",
      "Glitzer",
      "Dunkel",
      "Ewig",
      "Freiheit",
      "Erinnerung",
      "Sanftmut",
      "Schmerz",
      "Bereich",
      "Streichholz",
      "Fernweh",
      "Wissen",
      "Kunst",
      "Schmuck",
      "Delikt",
      "Unternehmung",
      "Schicksal",
      "Lasche",
      "Schräg",
      "Warm",
      "Schwarm",
      "Blau",
      "Pappe",
      "Weite",
      "Mut",
      "Freude",
      "Einwand",
      "Flaschenpost"
    ]
  },
  "minecraft_mobs": {
    "name": "Minecraft Mobs",
    "source": "http://https://www.digminecraft.com/mobs/index.php/",
    "values": [
      "Blaze",
      "Creeper",
      "Drowned",
      "Guardian",
      "Ender Dragon",
      "Endermite",
      "Evoker",
      "Ghast",
      "Hoglin",
      "Husk",
      "Illusioner",
      "Phantom",
      "Magma Cube",
      "Pigman",
      "Piglin",
      "Pillager",
      "Ravager",
      "Silverfish",
      "Shulker",
      "Skeleton",
      "Slime",
      "Stray",
      "Vex",
      "Vindicator",
      "Witch",
      "Wither",
      "Zoglin",
      "Zombie"
    ]
  }
};
