var categories = {
  "si_prefixes": {
    "name": "SI Prefixes",
    "source": "http://en.wikipedia.org/wiki/Metric_prefix",
    "values": [
      "yotta",
      "zetta",
      "exa",
      "peta",
      "tera",
      "giga",
      "mega",
      "kilo",
      "hecto",
      "deca",
      "deci",
      "centi",
      "milli",
      "micro",
      "nano",
      "pico",
      "femto",
      "atto",
      "zepto",
      "yocto"
    ]
  },
  "si_units": {
    "name": "SI Units",
    "source": "http://en.wikipedia.org/wiki/Outline_of_the_metric_system",
    "values": [
      "Abampere",
      "Abcoulomb",
      "Abhenry",
      "Abohm",
      "Abvolt",
      "Ampere",
      "Apostilb",
      "Astronomical",
      "Dalton",
      "Barye",
      "Becquerel",
      "Bril",
      "Candela",
      "Celsius",
      "Centimetre",
      "Coulomb",
      "Cubic",
      "Curie",
      "Day",
      "Decibel",
      "Degree",
      "Dyne",
      "Electronvolt",
      "Erg",
      "Farad",
      "Gal",
      "Gauss",
      "Gram",
      "Grave",
      "Gray",
      "Hectare",
      "Henry",
      "Hertz",
      "Hour",
      "Joule",
      "Katal",
      "Kelvin",
      "Kilogram",
      "Litre",
      "Lumen",
      "Lux",
      "Maxwell",
      "Metre",
      "Microgram",
      "Minute",
      "Mole",
      "Neper",
      "Newton",
      "Oersted",
      "Ohm",
      "Pascal",
      "Phot",
      "Poise",
      "Radian",
      "Rayleigh",
      "Roentgen",
      "Second",
      "Siemens",
      "Sievert",
      "Skot",
      "Square",
      "Statcoulomb",
      "Statvolt",
      "Steradian",
      "Stilb",
      "Torr",
      "Stokes",
      "Tesla",
      "Tonne",
      "Volt",
      "Watt",
      "Weber"
    ]
  },
  "elements": {
    "name": "Chemical Elements",
    "source": "https://en.wikipedia.org/wiki/List_of_elements",
    "values": [
      "Hydrogen",
      "Helium",
      "Lithium",
      "Beryllium",
      "Boron",
      "Carbon",
      "Nitrogen",
      "Oxygen",
      "Fluorine",
      "Neon",
      "Sodium",
      "Magnesium",
      "Aluminium",
      "Silicon",
      "Phosphorus",
      "Sulfur",
      "Chlorine",
      "Argon",
      "Potassium",
      "Calcium",
      "Scandium",
      "Titanium",
      "Vanadium",
      "Chromium",
      "Manganese",
      "Iron",
      "Cobalt",
      "Nickel",
      "Copper",
      "Zinc",
      "Gallium",
      "Germanium",
      "Arsenic",
      "Selenium",
      "Bromine",
      "Krypton",
      "Rubidium",
      "Strontium",
      "Yttrium",
      "Zirconium",
      "Niobium",
      "Molybdenum",
      "Technetium",
      "Ruthenium",
      "Rhodium",
      "Palladium",
      "Silver",
      "Cadmium",
      "ndium",
      "Tin",
      "Antimony",
      "Tellurium",
      "odine",
      "Xenon",
      "Caesium",
      "Barium",
      "Lanthanum",
      "Cerium",
      "Praseodymiu",
      "Neodymium",
      "Promethium",
      "Samarium",
      "Europium",
      "Gadolinium",
      "Terbium",
      "Dysprosium",
      "Holmium",
      "Erbium",
      "Thulium",
      "Ytterbium",
      "Lutetium",
      "Hafnium",
      "Tantalum",
      "Tungsten",
      "Rhenium",
      "Osmium",
      "ridium",
      "Platinum",
      "Gold",
      "Mercury",
      "Thallium",
      "Lead",
      "Bismuth",
      "Polonium",
      "Astatine",
      "Radon",
      "Francium",
      "Radium",
      "Actinium",
      "Thorium",
      "Protactinium",
      "Uranium",
      "Neptunium",
      "Plutonium",
      "Americium",
      "Curium",
      "Berkelium",
      "Californium",
      "Einsteinium",
      "Fermium",
      "Mendelevium",
      "Nobelium",
      "Lawrencium",
      "Rutherfordium",
      "Dubnium",
      "Seaborgium",
      "Bohrium",
      "Hassium",
      "Meitnerium",
      "Darmstadtium",
      "Roentgenium",
      "Copernicium",
      "Ununtrium",
      "Flerovium",
      "Ununpentium",
      "Livermorium",
      "Ununseptium",
      "Ununoctium"
    ]
  },
  "colors": {
    "name": "Colors (Basic)",
    "source": "https://simple.wikipedia.org/wiki/List_of_colors",
    "values": [
      "Beige",
      "Black",
      "Blue",
      "Bronze",
      "Brown",
      "Cyan",
      "Golden",
      "Gray",
      "Green",
      "Lilac",
      "Magenta",
      "Mauve",
      "Olive",
      "Orange",
      "Pink",
      "Purple",
      "Red",
      "Rose",
      "Silver",
      "Violet",
      "White",
      "Yellow"
    ]
  },
  "colors_extended": {
    "name": "Colors (Extended)",
    "source": "https://simple.wikipedia.org/wiki/List_of_colors",
    "values": [
      "Amaranth",
      "Amber",
      "Amethyst",
      "Apricot",
      "Aquamarine",
      "Azure",
      "Baby blue",
      "Beige",
      "Black",
      "Blue",
      "Blue-green",
      "Blue-violet",
      "Blush",
      "Bronze",
      "Brown",
      "Burgundy",
      "Byzantium",
      "Carmine",
      "Cerise",
      "Cerulean",
      "Champagne",
      "Chartreuse green",
      "Chocolate",
      "Cobalt blue",
      "Coffee",
      "Copper",
      "Coral",
      "Crimson",
      "Cyan",
      "Desert sand",
      "Electric blue",
      "Emerald",
      "Erin",
      "Gold",
      "Gray",
      "Green",
      "Harlequin",
      "Indigo",
      "Ivory",
      "Jade",
      "Jungle green",
      "Lavender",
      "Lemon",
      "Lilac",
      "Lime",
      "Magenta",
      "Magenta rose",
      "Maroon",
      "Mauve",
      "Navy blue",
      "Ocher",
      "Olive",
      "Orange",
      "Orange-red",
      "Orchid",
      "Peach",
      "Pear",
      "Periwinkle",
      "Persian blue",
      "Pink",
      "Plum",
      "Prussian blue",
      "Puce",
      "Purple",
      "Raspberry",
      "Red",
      "Red-violet",
      "Rose",
      "Ruby",
      "Salmon",
      "Sangria",
      "Sapphire",
      "Scarlet",
      "Silver",
      "Slate gray",
      "Spring bud",
      "Spring green",
      "Tan",
      "Taupe",
      "Teal",
      "Turquoise",
      "Violet",
      "Viridian",
      "White",
      "Yellow"
    ]
  },
  "us_state_flowers": {
    "name": "US State Flowers",
    "source": "http://en.wikipedia.org/wiki/List_of_U.S._state_flowers",
    "values": [
      "Camellia",
      "Oak-leaf hydrangea",
      "Forget-me-not",
      "Saguaro cactus blossom",
      "Apple blossom",
      "California poppy",
      "Columbine",
      "Mountain laurel",
      "Peach blossom",
      "Orange blossom",
      "Tickseed",
      "Cherokee Rose",
      "Azalea",
      "Hawaiian hibiscus",
      "Syringa",
      "Mock Orange",
      "Violet",
      "Peony",
      "Wild Prairie Rose",
      "Sunflower",
      "Goldenrod",
      "Magnolia",
      "Louisiana Iris",
      "Black-eyed susan",
      "Mayflower",
      "Apple blossom",
      "Dwarf Lake Iris",
      "Magnolia",
      "Tickseed",
      "Hawthorn",
      "Bitterroot",
      "Goldenrod",
      "Sagebrush",
      "Purple lilac",
      "Violet",
      "Yucca flower",
      "Rose",
      "Flowering Dogwood",
      "Wild Prairie Rose",
      "Scarlet Carnation",
      "Large white trillium",
      "Oklahoma Rose",
      "Mistletoe",
      "Indian Blanket",
      "Oregon grape",
      "Mountain Laurel",
      "Penngift Crown Vetch",
      "Violet",
      "Yellow Jessamine",
      "Goldenrod",
      "Pasque flower",
      "Iris",
      "Purple Passionflower",
      "Bluebonnet",
      "Sego lily",
      "Red Clover",
      "American Dogwood",
      "Coast Rhododendron",
      "Rhododendron",
      "Wood Violet"
    ]
  },
  "common_asians_names": {
    "name": "Common Asian Names",
    "source": "http://en.wikipedia.org/wiki/List_of_common_Chinese_surnames",
    "values": [
      "Lee",
      "Chen",
      "Wong",
      "Yang",
      "Wang",
      "Chang",
      "Chan",
      "Li",
      "Lin",
      "Liu",
      "Tan",
      "Lim",
      "Ng",
      "Ong",
      "Goh",
      "Chua",
      "Koh",
      "Teo",
      "Zhang",
      "Lam",
      "Leung",
      "Ho"
    ]
  },
  "impressive_chemistry": {
    "name": "Impressive Chemical Names",
    "source": "http://chemistry.about.com/od/chemicaldatabases/a/Chemical-Names-Of-Common-Substances.htm",
    "values": [
      "keton",
      "bisulfate",
      "acid",
      "hydroxide",
      "alcohol",
      "disulfide",
      "potassium",
      "oxide",
      "thiosulfate",
      "glycol",
      "trisulfide",
      "trioxide",
      "oxysulfide",
      "solution",
      "silicate",
      "bicarbonate",
      "acetate",
      "sulfate",
      "hydrogen",
      "chloride",
      "dichromate",
      "lim",
      "sulfat",
      "borat",
      "copper",
      "trichloride",
      "stanni",
      "chlorid",
      "dioxide",
      "carbonate",
      "nitrate",
      "hypochlorite",
      "bitartrate",
      "thiophosphate",
      "crystal ",
      "ferricyanide",
      "formaldehyd",
      "linseed",
      "cynanide",
      "thiosulfat",
      "hydroxid",
      "monoxide",
      "potash",
      "salicylate",
      "ferrocyanide",
      "acetoarsenite",
      "cyanide",
      "pyrophosphate",
      "tetraoxide",
      "acetat",
      "binoxalate",
      "dilut"
    ]
  },
  "fish": {
    "name": "Fish and Shellfish",
    "source": "http://www.schmidtzeevis.nl/html/fish_names_in_7_languages.html",
    "values": [
      "Anchovy",
      "Perch",
      "Flounder",
      "Trout",
      "Garfish",
      "Gilt Head Bream",
      "Brill",
      "Coding",
      "Shark",
      "Mullet",
      "Herring",
      "Hake",
      "Halibut",
      "Horse Mackerel",
      "Octopus",
      "Squid",
      "Cuttlefish",
      "Cod",
      "Carp",
      "Caviar",
      "Saithe",
      "Frostfish",
      "Ling",
      "Capelin",
      "Mackerel",
      "Marlin",
      "Catfisch",
      "Goatfish",
      "Moray",
      "Croaker",
      "Drum",
      "Meagre",
      "Joey",
      "Eel",
      "Parrot fish",
      "Sardinella",
      "Weever",
      "Pilchard",
      "Plaice",
      "Tub gurnard",
      "Gurnard",
      "Eelpout",
      "Ray",
      "Skate",
      "Red Bream",
      "Sailfish",
      "Brisling",
      "Dab",
      "Haddock",
      "Scorpionfish",
      "Sandeel",
      "Pike",
      "Pike-perch",
      "Smelt",
      "Sprat",
      "Pout",
      "Sturgeon",
      "Stockfish",
      "John Dory",
      "Turbot",
      "Sole",
      "Tuna",
      "Bonito",
      "Filefish",
      "Triggerfish",
      "Pollack",
      "Flying Fish",
      "Whiting",
      "Silver hake",
      "Salmon",
      "Sea Bass",
      "Grouper",
      "Sea Bream",
      "Anglerfish",
      "Tench",
      "Conger",
      "Catfish",
      "Shrimp",
      "Crab",
      "Lobster",
      "Crawfish",
      "Periwinkle",
      "Scallop",
      "Cockle",
      "Mussel",
      "Oyster",
      "Razor shell",
      "clam",
      "Carpet Shell",
      "Hard Clam",
      "Whelk"
    ]
  },
  "endangered_species": {
    "name": "Endangered Species",
    "source": "http://worldwildlife.org/species/directory?sort=extinction_status&direction=desc",
    "values": [
      "Amur Leopard",
      "Black Rhino",
      "Cross River Gorilla",
      "Hawksbill Turtle",
      "Javan Rhino",
      "Leatherback Turtle",
      "Mountain Gorilla",
      "Saola",
      "South China Tiger",
      "Sumatran Elephant",
      "Sumatran Orangutan",
      "Sumatran Rhino",
      "Sumatran Tiger",
      "Sumatran",
      "Vaquita",
      "Western Lowland Gorilla",
      "Yangtze Finless Porpoise",
      "African Wild Dog",
      "Amur Tiger",
      "Asian Elephant",
      "Bengal Tiger",
      "Black Spider Monkey",
      "Black-footed Ferret",
      "Blue Whale",
      "Bluefin Tuna",
      "Bonobo",
      "Bornean Orangutan",
      "Borneo Pygmy Elephant",
      "Chimpanzee",
      "Eastern Lowland Gorilla",
      "Fin Whale",
      "Galápagos Penguin",
      "Ganges River Dolphin",
      "Giant Panda",
      "Green Turtle",
      "Hector's Dolphin",
      "Humphead Wrasse",
      "Indian Elephant",
      "Indochinese Tiger",
      "Indus River Dolphin",
      "Loggerhead Turtle",
      "Malayan Tiger",
      "North Atlantic Right Whale",
      "Orangutan",
      "Sea Lions",
      "Sei Whale",
      "Snow Leopard",
      "Sri Lankan Elephant",
      "Tiger",
      "Whale",
      "African Elephant",
      "Bigeye Tuna",
      "Dugong",
      "Forest Elephant",
      "Giant Tortoise",
      "Great White Shark",
      "Greater One Horned Rhino",
      "Irrawaddy Dolphin",
      "Marine Iguana",
      "Olive Ridley Turtle",
      "Polar Bear",
      "Red Panda",
      "Savanna Elephant",
      "Southern rockhopper penguin",
      "Whale Shark",
      "Albacore Tuna",
      "Beluga",
      "Greater Sage-Grouse",
      "Jaguar",
      "Monarch Butterfly",
      "Mountain Plover",
      "Narwhal",
      "Plains Bison",
      "White Rhino",
      "Yellowfin Tuna",
      "Arctic Fox",
      "Arctic Wolf",
      "Bowhead Whale",
      "Brown Bear",
      "Gray Whale",
      "Macaw",
      "Pronghorn",
      "Skipjack Tuna",
      "Amazon River Dolphin",
      "Dolphins and Porpoises",
      "Elephant",
      "Gorilla",
      "Pacific Salmon",
      "Penguin",
      "Poison Dart Frog",
      "Rhino",
      "Sea Turtle",
      "Seals",
      "Shark",
      "Tree Kangaroo",
      "Tuna"
    ]
  },
  "squamata": {
    "name": "Scaled Reptiles Families",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427e7mnphgro3c",
    "values": [
      "Agamidae",
      "Amphisbaenia",
      "Amphisbaenidae",
      "Anguidae",
      "Anniellidae",
      "Chamaeleonidae",
      "Cordylidae",
      "Corytophanidae",
      "Crotaphytidae",
      "Dibamidae",
      "Gekkonidae",
      "Gerrhosauridae",
      "Gymnophthalmidae",
      "Helodermatidae",
      "Hoplocercidae",
      "Hydrophiidae",
      "Iguanidae",
      "Lacertidae",
      "Lanthanotidae",
      "Opluridae",
      "Phrynosomatidae",
      "Polychrotidae",
      "Pygopodidae",
      "Rhineuridae",
      "Scincidae",
      "Teiidae",
      "Tropiduridae",
      "Varanidae",
      "Xantusiidae",
      "Xenosauridae",
      "Henophidia",
      "Xenophidia"
    ]
  },
  "us_copycats_counties": {
    "name": "Some US Counties",
    "source": "http://en.wikipedia.org/wiki/List_of_U.S._counties_named_after_other_U.S._counties",
    "values": [
      "Albany",
      "Champaign",
      "Christian",
      "Genesee",
      "Hardin",
      "Henderson",
      "Lancaster",
      "Lincoln",
      "Mason",
      "Oneida",
      "Orange",
      "Otsego",
      "Richland",
      "Williamson",
      "Woodford",
      "York"
    ]
  },
  "national_capitals": {
    "name": "National Capitals",
    "source": "http://en.wikipedia.org/wiki/List_of_national_capitals_in_alphabetical_order",
    "values": [
      "Abu Dhabi",
      "Abuja",
      "Accra",
      "Adamstown",
      "Addis Ababa",
      "Algiers",
      "Alofi",
      "Amman",
      "Amsterdam",
      "Andorra la Vella",
      "Ankara",
      "Antananarivo",
      "Apia",
      "Ashgabat",
      "Asmara",
      "Astana",
      "Asunción",
      "Athens",
      "Avarua",
      "Baghdad",
      "Baku",
      "Bamako",
      "Bandar Seri Begawan",
      "Bangkok",
      "Bangui",
      "Banjul",
      "Basseterre",
      "Beijing",
      "Beirut",
      "Belgrade",
      "Belmopan",
      "Berlin",
      "Bern",
      "Bishkek",
      "Bissau",
      "Bogotá",
      "Brasília",
      "Bratislava",
      "Brazzaville",
      "Bridgetown",
      "Brussels",
      "Bucharest",
      "Budapest",
      "Buenos Aires",
      "Bujumbura",
      "Cairo",
      "Canberra",
      "Caracas",
      "Castries",
      "Cayenne",
      "Charlotte Amalie",
      "Chisinau",
      "Cockburn Town",
      "Conakry",
      "Copenhagen",
      "Dakar",
      "Damascus",
      "Dhaka",
      "Dili",
      "Djibouti",
      "Doha",
      "Douglas",
      "Dublin",
      "Dushanbe",
      "Edinburgh of the Seven Seas",
      "El Aaiún",
      "Episkopi Cantonment",
      "Flying Fish Cove",
      "Freetown",
      "Funafuti",
      "Gaborone",
      "George Town",
      "Georgetown",
      "Georgetown",
      "Gibraltar",
      "Grytviken",
      "Guatemala City",
      "Gustavia",
      "Hagåtña",
      "Hamilton",
      "Hanga Roa",
      "Hanoi",
      "Harare",
      "Hargeisa",
      "Havana",
      "Helsinki",
      "Honiara",
      "Islamabad",
      "Jakarta",
      "Jamestown",
      "Jerusalem",
      "Ramallah and Gaza",
      "Juba",
      "Kabul",
      "Kampala",
      "Kathmandu",
      "Khartoum",
      "Kiev",
      "Kigali",
      "Kingston",
      "Kingston",
      "Kingstown",
      "Kinshasa",
      "Kuala Lumpur",
      "Putrajaya",
      "Kuwait City",
      "Libreville",
      "Lilongwe",
      "Lima[h]",
      "Lisbon",
      "Ljubljana",
      "Lomé",
      "London",
      "Luanda",
      "Lusaka",
      "Luxembourg",
      "Madrid",
      "Majuro",
      "Malabo",
      "Malé",
      "Managua",
      "Manama",
      "Manila",
      "Maputo",
      "Marigot",
      "Maseru",
      "Mata-Utu",
      "Mbabane",
      "Lobamba",
      "Melekeok",
      "Ngerulmud",
      "Mexico City",
      "Minsk",
      "Mogadishu",
      "Monaco",
      "Monrovia",
      "Montevideo",
      "Moroni",
      "Moscow",
      "Muscat",
      "Nairobi",
      "Nassau",
      "Naypyidaw",
      "N'Djamena",
      "New Delhi",
      "Niamey",
      "Nicosia",
      "Nicosia",
      "Nouakchott",
      "Nouméa",
      "Nukuʻalofa",
      "Nuuk",
      "Oranjestad",
      "Oslo",
      "Ottawa",
      "Ouagadougou",
      "Pago Pago",
      "Palikir",
      "Panama City",
      "Papeete",
      "Paramaribo",
      "Paris",
      "Philipsburg",
      "Phnom Penh",
      "Plymouth",
      "Brades Estate",
      "Podgorica",
      "Cetinje",
      "Port Louis",
      "Port Moresby",
      "Port Vila",
      "Port-au-Prince",
      "Port of Spain",
      "Porto-Novo",
      "Cotonou",
      "Prague",
      "Praia",
      "Pretoria",
      "Bloemfontein",
      "Cape Town",
      "Pristina",
      "Pyongyang",
      "Quito",
      "Rabat",
      "Reykjavík",
      "Riga",
      "Riyadh",
      "Road Town",
      "Rome",
      "Roseau",
      "Saipan",
      "San José",
      "San Juan",
      "San Marino",
      "San Salvador",
      "Sana'a",
      "Santiago",
      "Valparaíso",
      "Santo Domingo",
      "São Tomé",
      "Sarajevo",
      "Seoul",
      "Singapore",
      "Skopje",
      "Sofia",
      "Colombo",
      "St. George's",
      "St. Helier",
      "St. John's",
      "St. Peter Port",
      "St. Pierre",
      "Stanley",
      "Stepanakert",
      "Stockholm",
      "Sucre",
      "La Paz",
      "Sukhumi",
      "Suva",
      "Taipei",
      "Tallinn",
      "Tarawa",
      "Tashkent",
      "Tbilisi",
      "Kutaisi",
      "Tegucigalpa",
      "Tehran",
      "Thimphu",
      "Tirana",
      "Tiraspol",
      "Tokyo",
      "Tórshavn",
      "Tripoli",
      "Tskhinvali",
      "Tunis",
      "Ulan Bator",
      "Vaduz",
      "Valletta",
      "The Valley",
      "Vatican City",
      "Victoria",
      "Vienna",
      "Vientiane",
      "Vilnius",
      "Warsaw",
      "Washington",
      "Wellington",
      "West Island",
      "Willemstad",
      "Windhoek",
      "Abidjan",
      "Yaoundé",
      "Yaren",
      "Yerevan",
      "Zagreb"
    ]
  },
  "cats": {
    "name": "Cats",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427emme6ununpd",
    "values": [
      "Chausie",
      "British Longhair",
      "Maine Coon",
      "Bengal",
      "York Chocolate",
      "Ragdoll",
      "Highlander",
      "Siberian",
      "Ragamuffin",
      "Norwegian Forest Cat",
      "Pixie‐Bob",
      "California Spangled Cat",
      "British Shorthair",
      "Turkish Van",
      "Birman",
      "Australian Mist",
      "Chartreux",
      "Burmilla",
      "Abyssinian",
      "European Shorthair",
      "Oriental Longhair",
      "American Shorthair",
      "Himalayan",
      "Persian",
      "American Wirehair",
      "Sphynx",
      "Tiffanie",
      "Sokoke",
      "American Bobtail",
      "German Rex",
      "Exotic Shorthair",
      "Chinese Li Hua Mao",
      "Burmese",
      "European Burmese",
      "Oriental Shorthair",
      "Ocicat",
      "Kurilian Bobtail",
      "Cymric",
      "Manx",
      "Scottish Fold",
      "LaPerm",
      "Somali",
      "Siamese Traditional",
      "Toyger",
      "Ojos Azules",
      "Donskoy",
      "Serengeti",
      "Siamese Modern",
      "Tonkinese",
      "Snowshoe",
      "Selkirk Rex",
      "Chantilly",
      "Bombay",
      "American Curl",
      "Peterbald",
      "Russian Blue",
      "Javanese",
      "Turkish Angora",
      "Balinese",
      "Korats",
      "Havana Brown",
      "Nebelung",
      "Egyptian Mau",
      "Cornish Rex",
      "Minskin",
      "Munchkin",
      "Japanese Bobtail",
      "Devon Rex",
      "Colorpoint Shorthair",
      "Singapura"
    ]
  },
  "jazz_first": {
    "name": "Jazz Firstnames",
    "source": "https://en.wikipedia.org/wiki/List_of_jazz_musicians",
    "values": [
      "Scott",
      "Charles",
      "Duke",
      "Louis",
      "Joe",
      "Earl",
      "Fats",
      "Count",
      "Stephane",
      "Benny",
      "Art",
      "Sun",
      "Ward",
      "Thelonious",
      "Dizzy",
      "Clark",
      "Charlie",
      "Dave",
      "Charles",
      "Oscar",
      "Miles",
      "John",
      "Gerry",
      "Chet",
      "Ornette",
      "Wynton"
    ]
  },
  "jazz_last": {
    "name": "Jazz Lastnames",
    "source": "https://en.wikipedia.org/wiki/List_of_jazz_musicians",
    "values": [
      "Joplin",
      "Bolden",
      "Ellington",
      "Armstrong",
      "Venuti",
      "Hines",
      "Waller",
      "Basie",
      "Grappelli",
      "Goodman",
      "Tatum",
      "Ra",
      "Kimball",
      "Monk",
      "Gillespie",
      "Terry",
      "Parker",
      "Brubeck",
      "Mingus",
      "Peterson",
      "Davis",
      "Coltrane",
      "Mulligan",
      "Baker",
      "Coleman",
      "Marsalis"
    ]
  },
  "blues_names": {
    "name": "Blues Nicknames",
    "source": "http://www.outliermusic.com/jokes_bluesname.htm",
    "values": [
      "Bones",
      "Money",
      "Harp",
      "Legs",
      "Eyes",
      "Lemon",
      "Killer",
      "Hips",
      "Lips",
      "Fingers",
      "Boy",
      "Liver",
      "Gumbo",
      "Foot",
      "Mama",
      "Back",
      "Duke",
      "Dog",
      "Bad Boy",
      "Baby",
      "Chicken",
      "Pickles",
      "Sugar",
      "Cracker",
      "Tooth",
      "Smoke ",
      "Huh",
      "Fat",
      "Muddy",
      "Crippled",
      "Old",
      "Texas",
      "Hollerin'",
      "Ugly",
      "Brown",
      "Happy",
      "Boney",
      "Curly",
      "Pretty",
      "Jailhouse",
      "Peg Leg",
      "Red",
      "Sleepy",
      "Bald",
      "Skinny",
      "Blind",
      "Big",
      "Yella",
      "Toothless",
      "Screamin'",
      "Fat Boy",
      "Washboard",
      "Steel-Eye",
      "Jackson",
      "McGee",
      "Hopkins",
      "Dupree",
      "Green",
      "Jones",
      "Rivers",
      "Malone",
      "Washington",
      "Smith",
      "Parker",
      "Lee",
      "Thompkins",
      "King",
      "Bradley",
      "Hawkins",
      "Jefferson",
      "Davis",
      "Franklin",
      "White",
      "Jenkins",
      "Bailey",
      "Johnson",
      "Blue",
      "Allison",
      "Huh"
    ]
  },
  "flowers": {
    "name": "Flowers",
    "source": "http://www.whatiscalled.com/flower-names-in-all-languages/",
    "values": [
      "Arabian Jasmine",
      "Lily",
      "Buttercups",
      "China Rose",
      "Cobra Saffron",
      "Crossandra",
      "Cypress Vine",
      "Daffodils",
      "Dahlia",
      "Daisy",
      "Damask Rose",
      "Datura",
      "Creeper",
      "Jasmine",
      "Four O'clock",
      "Frangipani",
      "Gallant Soldier",
      "Galinsoga Parviflora",
      "Globe Amaranth",
      "Golden Champa",
      "Indian Tulip",
      "Ixora",
      "Kewda",
      "Kurinji",
      "Violet",
      "Lotus",
      "Maloo Creeper",
      "Maulsari",
      "Midday Flower",
      "Oleander",
      "Peacock Flower",
      "Periwinkle",
      "Myrtle",
      "Rose",
      "Star Jasmine",
      "Sunflower",
      "Cassia",
      "Tulips",
      "Water Lily",
      "Bougainvillea",
      "Zinnia",
      "Ceylon Ironwood",
      "Bullet Wood",
      "Chrysanthemum",
      "Cockscomb",
      "Amaranth",
      "Pine",
      "Ghanera",
      "Hiptage",
      "Hummingbird Vine",
      "Chestnut",
      "Jungle Flame",
      "Pink Jasmine",
      "Star Glory",
      "Superb Lily",
      "Artichoke",
      "Chamomile",
      "Cannabis",
      "Citrus",
      "Blossoms",
      "Clover",
      "Dandelions",
      "Daylily",
      "Elderflower",
      "Hibiscus",
      "Honeysuckle",
      "Nasturtium",
      "Sweet",
      "Osmanthus",
      "Pansy",
      "Calendula",
      "Officinalis",
      "Sesbania",
      "Grandiflora",
      "Zucchini",
      "Aurantiaca",
      "Alba"
    ]
  },
  "animals": {
    "name": "Animals",
    "source": "http://tamilcube.com/res/indian_animals.html",
    "values": [
      "Ant",
      "Bear",
      "Buffalo",
      "Butterfly",
      "Camel",
      "Cat",
      "Chameleon",
      "Chimpanzee",
      "Cow",
      "Crocodile",
      "Crab",
      "Deer",
      "Dog",
      "Donkey",
      "Elephant",
      "Fox",
      "Frog",
      "Goat",
      "Gorilla",
      "Horse",
      "Hippopotamus",
      "Jackal",
      "Lion",
      "Lizard",
      "Mongoose",
      "Monkey",
      "mosquito",
      "Mouse",
      "Ox",
      "Pig",
      "Polar Bear",
      "Rabbit",
      "Rat",
      "Rhinoceros",
      "Sheep",
      "Snail",
      "Snake",
      "Spider",
      "Squirrel",
      "Tiger",
      "Turtle",
      "Wolf"
    ]
  },
  "imperial": {
    "name": "Imperial Units",
    "source": "http://wiki.answers.com/Q/List_of_imperial_units",
    "values": [
      "pound",
      "ounce",
      "thou",
      "inch",
      "foot",
      "yard",
      "chain",
      "furlong",
      "mile",
      "league",
      "fathom",
      "cable",
      "nautical",
      "link",
      "rod",
      "perch",
      "rood",
      "acre",
      "gill",
      "pint",
      "quart",
      "gallon",
      "minim",
      "scruple",
      "drachm",
      "grain",
      "stone",
      "quarter",
      "hundredweight",
      "ton"
    ]
  },
  "california_cities": {
    "name": "Californian Cities",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427eue1f1uq3b4",
    "values": [
      "Bakersfield",
      "Anaheim",
      "Santa Ana",
      "Riverside",
      "Stockton",
      "ChuVista",
      "Fremont",
      "Irvine",
      "Modesto",
      "Oxnard",
      "Fontana",
      "Moreno",
      "Glendale",
      "Huntington",
      "Clarita",
      "Rosa",
      "Oceanside",
      "Cucamonga",
      "Ontario",
      "Lancaster",
      "Elk Grove",
      "Palmdale",
      "Corona",
      "Salinas",
      "Pomona",
      "Torrance",
      "Hayward",
      "Escondido",
      "Sunnyvale",
      "Pasadena",
      "Orange",
      "Fullerton",
      "Visalia",
      "Valley",
      "Concord",
      "Roseville",
      "Clara",
      "Vallejo",
      "Victorville",
      "Monte",
      "Berkeley",
      "Downey",
      "Mesa",
      "Inglewood",
      "Covina",
      "Norwalk",
      "Carlsbad",
      "Fairfield",
      "Richmond",
      "Murrieta",
      "Burbank",
      "Antioch",
      "Daly",
      "Temecula",
      "Maria",
      "Cajon",
      "Rialto",
      "Mateo",
      "Compton",
      "Clovis",
      "Gate",
      "Vista",
      "Viejo",
      "Vacaville",
      "Arden",
      "Carson",
      "Hesperia",
      "Redding",
      "Monica",
      "Westminster",
      "Barbara",
      "Chico",
      "Whittier",
      "Newport",
      "Leandro",
      "Hawthorne",
      "Marcos",
      "Citrus",
      "Alhambra",
      "Tracy",
      "Livermore",
      "Buena",
      "Lakewood",
      "Merced",
      "Hemet",
      "Chino",
      "Napa",
      "Redwood",
      "Bellflower",
      "Indio",
      "Tustin",
      "Baldwin",
      "Chino",
      "Mountain View",
      "Alameda",
      "Upland",
      "Folsom",
      "Ramon",
      "Pleasanton",
      "Lynwood",
      "Union",
      "Redlands",
      "Turlock",
      "Perris",
      "Manteca",
      "Milpitas",
      "Redondo",
      "Davis",
      "Camarillo",
      "Yuba",
      "Cordova",
      "Palo Alto",
      "Yorba Linda",
      "Walnut Creek",
      "Clemente",
      "Florence-Graham",
      "Pittsburg",
      "Laguna Niguel",
      "Pico Rivera",
      "Montebello",
      "Lodi",
      "Carmichael",
      "Madera",
      "Castro",
      "Monterey",
      "Habra",
      "Santa Cruz",
      "Encinitas",
      "Tulare",
      "Gardena",
      "Cupertino",
      "Huntington",
      "Petaluma",
      "Rafael",
      "Whittier",
      "Mesa",
      "Rocklin",
      "Arcadia",
      "Diamond",
      "Woodland",
      "Fountain",
      "Porterville",
      "Paramount",
      "Hacienda",
      "Hanford",
      "Rosemead",
      "Santee",
      "Highland",
      "Delano",
      "Colton",
      "Novato",
      "Elsinore",
      "Brentwood",
      "Yucaipa",
      "Cathedral",
      "Watsonville",
      "Placentia",
      "Glendora"
    ]
  },
  "metals": {
    "name": "Metals",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427e48dr7di6c2",
    "values": [
      "lithium",
      "beryllium",
      "sodium",
      "magnesium",
      "aluminum",
      "potassium",
      "calcium",
      "scandium",
      "titanium",
      "vanadium",
      "chromium",
      "manganese",
      "iron",
      "cobalt",
      "nickel",
      "copper",
      "zinc",
      "gallium",
      "arsenic",
      "rubidium",
      "strontium",
      "yttrium",
      "zirconium",
      "niobium",
      "molybdenum",
      "technetium",
      "ruthenium",
      "rhodium",
      "palladium",
      "silver",
      "cadmium",
      "indium",
      "tin",
      "antimony",
      "cesium",
      "barium",
      "lanthanum",
      "cerium",
      "praseodymium",
      "neodymium",
      "promethium",
      "samarium",
      "europium",
      "gadolinium",
      "terbium",
      "dysprosium",
      "holmium",
      "erbium",
      "thulium",
      "ytterbium",
      "lutetium",
      "hafnium",
      "tantalum",
      "tungsten",
      "rhenium",
      "osmium",
      "iridium",
      "platinum",
      "gold",
      "mercury",
      "thallium",
      "lead",
      "bismuth",
      "polonium",
      "francium",
      "radium",
      "actinium",
      "thorium",
      "protactinium",
      "uranium",
      "neptunium",
      "plutonium",
      "americium",
      "curium",
      "berkelium",
      "californium",
      "einsteinium",
      "fermium",
      "mendelevium",
      "nobelium",
      "lawrencium",
      "rutherfordium",
      "dubnium",
      "seaborgium",
      "bohrium",
      "hassium",
      "meitnerium",
      "darmstadtium",
      "roentgenium",
      "copernicium",
      "ununtrium",
      "flerovium",
      "ununpentium",
      "livermorium"
    ]
  },
  "dogs": {
    "name": "Dog Breeds",
    "source": "https://en.wikipedia.org/wiki/List_of_most_popular_dog_breeds",
    "values": [
      "Labrador",
      "Retriever",
      "Cocker Spaniel",
      "Springer Spaniel",
      "German Shepherd",
      "Bull Terrier",
      "Spaniel",
      "Golden Retriever",
      "White Terrier",
      "Boxer",
      "Border Terrier",
      "Rottweiler",
      "Shih Tzu",
      "Miniature Schnauzer",
      "Lhasa Apso",
      "Yorkshire Terrier",
      "Bulldog",
      "Dobermann Pinscher",
      "Weimaraner",
      "Pug",
      "Whippet",
      "Bichon Frise",
      "Border Collie",
      "Siberian Husky",
      "Shar-Pei",
      "Dalmatian",
      "Great Dane",
      "Cairn Terrier",
      "Beagle",
      "Dachshund",
      "Poodle",
      "Chihuahua",
      "Pomeranian",
      "Boston Terrier",
      "Maltese",
      "Shorthaired Pointer",
      "Shetland Sheepdog",
      "Doberman Pinscher",
      "Welsh Corgi",
      "Miniature Pinscher",
      "Basset Hound"
    ]
  },
  "animal_babies": {
    "name": "Animal Babies",
    "source": "https://en.wikipedia.org/wiki/List_of_animal_names",
    "values": [
      "cub",
      "chick",
      "hatchling",
      "cria",
      "larva",
      "pupa",
      "pup",
      "calf",
      "infant",
      "baby",
      "foal",
      "kit",
      "kitten",
      "piglet",
      "farrow",
      "shoat",
      "shote",
      "caterpillar",
      "chrysalis",
      "nymph",
      "codling",
      "sprat",
      "shaglet",
      "whelp",
      "colt",
      "fawn",
      "juvenile",
      "puppy",
      "duckling",
      "eaglet",
      "fledgling",
      "puggle",
      "leptocephalus",
      "elver",
      "eyass",
      "eyas",
      "fry",
      "fingerling",
      "maggot",
      "polliwog",
      "tadpole",
      "froglet",
      "kid",
      "gosling",
      "chulengo",
      "keet",
      "leveret",
      "hoglet",
      "larvae",
      "pupae",
      "filly",
      "gelding",
      "child",
      "girl",
      "boy",
      "planula",
      "polyp",
      "ephyra",
      "joey",
      "pinky",
      "fuzzy",
      "crawler",
      "hopper",
      "wriggler",
      "tumbler",
      "eft",
      "owlet",
      "spat",
      "peachick",
      "nestling",
      "barrow",
      "gilt",
      "squab",
      "squeaker",
      "bunny",
      "lamb",
      "salamanderling",
      "seafoal",
      "lambkin",
      "cosset",
      "shrewlet",
      "snakelet",
      "neonate",
      "spiderling",
      "cygnet",
      "flapper",
      "toadlet",
      "poult",
      "wormlet"
    ]
  },
  "kingdom_animalia": {
    "name": "Kingdom Animalia",
    "source": "http://www.wolframalpha.com/share/clip?f=d41d8cd98f00b204e9800998ecf8427ekhnrbufb4a",
    "values": [
      "Acanthocephala",
      "Annelida",
      "Arthropoda",
      "Brachiopoda",
      "Cephalorhyncha",
      "Chaetognatha",
      "Cnidaria",
      "Ctenophora",
      "Cycliophora",
      "Echinodermata",
      "Echiura",
      "Ectoprocta",
      "Entoprocta",
      "Gastrotricha",
      "Gnathostomulida",
      "Hemichordata",
      "Mesozoa",
      "Mollusca",
      "Myxozoa",
      "Nemata",
      "Nemertea",
      "Phoronida",
      "Placozoa",
      "Platyhelminthes",
      "Porifera",
      "Rotifera",
      "Sipuncula",
      "Tardigrada"
    ]
  },
  "greek_gods": {
    "name": "Greek Gods",
    "source": "https://simple.wikipedia.org/wiki/List_of_Greek_gods_and_goddesses",
    "values": [
      "Chaos",
      "Erebus",
      "Gaia",
      "Nyx",
      "Tartarus",
      "Ouranos",
      "Thesis",
      "Phanes",
      "Anemois",
      "Boreas",
      "Kaikias",
      "Apeliotes",
      "Euros",
      "Notos",
      "Lips",
      "Zephyrus",
      "Skirion",
      "Hemera",
      "Zeus",
      "Hades",
      "Poseidon",
      "Hera",
      "Dementer",
      "Hestia",
      "Aphrodite",
      "Apollo",
      "Ares",
      "Artemis",
      "Athena",
      "Demeter",
      "Dionysus",
      "Hephaestus",
      "Hermes"
    ]
  },
  "greek_titans": {
    "name": "Greek Titans",
    "source": "https://simple.wikipedia.org/wiki/List_of_Greek_gods_and_goddesses",
    "values": [
      "Koios",
      "Kreios",
      "Kronos",
      "Hyperion",
      "Iapetos",
      "Mnemosyne",
      "Oceanus",
      "Phoebe",
      "Rhea",
      "Tethys",
      "Theia",
      "Themis",
      "Atlas",
      "Epimetheus",
      "Menoitios",
      "Prometheus",
      "Asteria",
      "Perses",
      "Asterious",
      "Dione"
    ]
  },
  "us_submarines": {
    "name": "US Submarine Classes",
    "source": "https://en.wikipedia.org/wiki/List_of_submarine_classes_of_the_United_States_Navy",
    "values": [
      "Alligator",
      "Holland",
      "Plunger",
      "Barracuda",
      "Argonaut",
      "Narwhal",
      "Dolphin",
      "Cachalot",
      "Porpoise",
      "Salmon",
      "Sargo",
      "Tambor",
      "Mackerel",
      "Gato",
      "Balao",
      "Tench",
      "Barracuda",
      "Tang",
      "Albacore",
      "Nautilus",
      "Sailfish",
      "Grayback",
      "Seawolf",
      "Darter",
      "Skate",
      "Barbel",
      "Skipjack",
      "Triton",
      "Halibut",
      "Thresher",
      "Permit",
      "Tullibee",
      "Lafayette",
      "Dolphin",
      "Sturgeon",
      "Narwhal",
      "Ohio",
      "Seawolf",
      "Virginia"
    ]
  },
  "german_words": {
    "name": "German Words",
    "source": "http://pascalhertleif.de/",
    "values": [
      "Vogel",
      "Topf",
      "Mond",
      "Nacht",
      "Mondschein",
      "Sanft",
      "Hast",
      "Teil",
      "Sonne",
      "Leben",
      "Aus",
      "Feuer",
      "Reise",
      "Morgenstern",
      "Asche",
      "Engel",
      "Herz",
      "Rosenrot",
      "Wahrheit",
      "Flammen",
      "Regen",
      "Wort",
      "Geheimnis",
      "Kraft",
      "Preis",
      "Wirklich",
      "Glitzer",
      "Dunkel",
      "Ewig",
      "Freiheit",
      "Erinnerung",
      "Sanftmut",
      "Schmerz",
      "Bereich",
      "Streichholz",
      "Fernweh",
      "Wissen",
      "Kunst",
      "Schmuck",
      "Delikt",
      "Unternehmung",
      "Schicksal",
      "Lasche",
      "Schräg",
      "Warm",
      "Schwarm",
      "Blau",
      "Pappe",
      "Weite",
      "Mut",
      "Freude",
      "Einwand",
      "Flaschenpost"
    ]
  },
  "common_german_words": {
    "name": "Common German Words",
    "source": "http://frequencylists.blogspot.com/2015/12/the-2000-most-frequent-german-nouns.html",
    "values": [
      "Abend",
      "Abendessen",
      "Abenteuer",
      "Absicht",
      "Absturz",
      "Abteilung",
      "Abwesenheit",
      "Abzug",
      "Achselzucken",
      "Achsschenkel",
      "Adler",
      "Adresse",
      "Affäre",
      "Affe",
      "Agent",
      "Agentur",
      "Akt",
      "Aktentasche",
      "Aktie",
      "Aktion",
      "Aktivität",
      "Akzent",
      "Albtraum",
      "Alkohol",
      "Allgemeine",
      "Altar",
      "Ameise",
      "Anfang",
      "Anforderung",
      "Angebot",
      "Angel",
      "Angestellte",
      "Angewohnheit",
      "Angriff",
      "Angst",
      "Anhänger",
      "Anhörung",
      "Ankunft",
      "Anleitung",
      "Anruf",
      "Ansatz",
      "Anspruch",
      "Ansturm",
      "Antwort",
      "Anwalt",
      "Anwesen",
      "Anzahl",
      "Anzug",
      "Apfel",
      "Arbeit",
      "Arbeiter",
      "Arbeitnehmer",
      "Argument",
      "Arm",
      "Armee",
      "Artikel",
      "Asche",
      "Aspekt",
      "Assistent",
      "Ast",
      "Atem",
      "Atmosphäre",
      "Attitüde",
      "Auffahrt",
      "Aufgabe",
      "Aufgang",
      "Aufmerksamkeit",
      "Aufnehmer",
      "Aufprall",
      "Aufregung",
      "Aufwand",
      "Aufzug",
      "Auge",
      "Augenbraue",
      "Augenlid",
      "Ausdruck",
      "Ausgang",
      "Ausrüstung",
      "Aussage",
      "Aussehen",
      "Aussicht",
      "Austausch",
      "Auto",
      "Autobahn",
      "Autor",
      "Autorität",
      "Baby",
      "Bach",
      "Backofen",
      "Bahnhof",
      "Balance",
      "Balkon",
      "Ball",
      "Ballon",
      "Band",
      "Bank",
      "Bär",
      "Barkeeper",
      "Barmherzigkeit",
      "Bart",
      "Basis",
      "Bastard",
      "Batterie",
      "Bauch",
      "Bauer",
      "Bauernhof",
      "Baum",
      "Baumwolle",
      "Becher",
      "Bedauern",
      "Bedeutung",
      "Bedingung",
      "Bedrohung",
      "Bedürfnis",
      "Befehl",
      "Begegnung",
      "Begeisterung",
      "Begleiter",
      "Begräbnis",
      "Begriff",
      "Begrüßung",
      "Behandlung",
      "Bein",
      "Beispiel",
      "Bekleidung",
      "Bemerkung",
      "Beobachtung",
      "Bereich",
      "Berg",
      "Bericht",
      "Beruf",
      "Berührung",
      "Besatzung",
      "Beschreibung",
      "Beschwerde",
      "Besitz",
      "Bestellung",
      "Besuch",
      "Besucher",
      "Betreiber",
      "Bett",
      "Beutel",
      "Bevölkerung",
      "Bewegung",
      "Beweis",
      "Bewohner",
      "Bewusstsein",
      "Beziehung",
      "Bibel",
      "Bibliothek",
      "Biene",
      "Bier",
      "Biest",
      "Bild",
      "Bildschirm",
      "Bildung",
      "Bindung",
      "Bischof",
      "Biss",
      "Blase",
      "Blatt",
      "Blaue",
      "Bleistift",
      "Blendung",
      "Blick",
      "Blitz",
      "Block",
      "Blume",
      "Bluse",
      "Blut",
      "Bluterguss",
      "Boden",
      "Bogen",
      "Bogenschütze",
      "Bohne",
      "Bolzen",
      "Bombe",
      "Boot",
      "Börse",
      "Böse",
      "Braut",
      "Bremse",
      "Brief",
      "Brise",
      "Brot",
      "Brücke",
      "Bruder",
      "Brunnen",
      "Brust",
      "Buch",
      "Bucht",
      "Büffel",
      "Bügeleisen",
      "Bühne",
      "Bulle",
      "Bündel",
      "Burg",
      "Bürger",
      "Bürgermeister",
      "Bürgersteig",
      "Büro",
      "Bus",
      "Busch",
      "Butter",
      "Champagner",
      "Charakter",
      "Chef",
      "China",
      "Cousin",
      "Dach",
      "Dachboden",
      "Dame",
      "Dämmerung",
      "Dämon",
      "Dampf",
      "Dank",
      "Datei",
      "Daten",
      "Datensatz",
      "Datum",
      "Daumen",
      "Deck",
      "Decke",
      "Deckel",
      "Dekan",
      "Denken",
      "Depression",
      "Detail",
      "Detektiv",
      "Diagramm",
      "Diamant",
      "Dichtung",
      "Dieb",
      "Diener",
      "Dienstmädchen",
      "Diner",
      "Ding",
      "Dinosaurier",
      "Direktor",
      "Diskussion",
      "Distanz",
      "Dock",
      "Doktor",
      "Dokument",
      "Donner",
      "Dorf",
      "Dose",
      "Drache",
      "Drama",
      "Drang",
      "Dreck",
      "Druck",
      "Dschungel",
      "Duft",
      "Dummkopf",
      "Dunkelheit",
      "Durchgang",
      "Durchhang",
      "Durchschnitt",
      "Dusche",
      "Ebene",
      "Echo",
      "Ecke",
      "Effekt",
      "Ehe",
      "Ehefrau",
      "Ehemann",
      "Ehepaar",
      "Ehre",
      "Ei",
      "Eiche",
      "Eichhörnchen",
      "Eigenschaft",
      "Eile",
      "Eimer",
      "Eindruck",
      "Eine",
      "Eingang",
      "Eingeweide",
      "Einheit",
      "Einkaufen",
      "Einkaufshalle",
      "Einladung",
      "Einrichtung",
      "Einsatz",
      "Einstellung",
      "Eintritt",
      "Einzelne",
      "Eis",
      "Eisenbahn",
      "Ekel",
      "Elefant",
      "Element",
      "Elend",
      "Elf",
      "Ellbogen",
      "Elternteil",
      "Emotion",
      "Empfänger",
      "Ende",
      "Energie",
      "Engel",
      "Ente",
      "Entscheidung",
      "Entschuldigung",
      "Enttäuschung",
      "Entwicklung",
      "Entwurf",
      "Erde",
      "Ereignis",
      "Erfolg",
      "Ergebnis",
      "Erkennung",
      "Erklärung",
      "Erlaubnis",
      "Erlebnis",
      "Ermittlung",
      "Eröffnung",
      "Erscheinung",
      "Erwachsene",
      "Erzähler",
      "Esel",
      "Essen",
      "Eule",
      "Exekutive",
      "Existenz",
      "Experte",
      "Explosion",
      "Fabrik",
      "Fach",
      "Fackel",
      "Faden",
      "Fähigkeit",
      "Fahrer",
      "Fahrrad",
      "Fahrspur",
      "Fahrt",
      "Fahrzeug",
      "Fall",
      "Falle",
      "Falte",
      "Familie",
      "Fantasie",
      "Farbband",
      "Farbe",
      "Faust",
      "Favorit",
      "Fazit",
      "Feder",
      "Fee",
      "Fehl",
      "Fehler",
      "Feind",
      "Feld",
      "Fell",
      "Fels",
      "Fenster",
      "Fernsehen",
      "Ferse",
      "Festung",
      "Fett",
      "Feuer",
      "Fieber",
      "Figur",
      "Fiktion",
      "Film",
      "Finger",
      "Fingernagel",
      "Firma",
      "Fisch",
      "Flagge",
      "Flamme",
      "Flasche",
      "Fleck",
      "Fledermaus",
      "Fleisch",
      "Fliese",
      "Flotte",
      "Fluch",
      "Flucht",
      "Flug",
      "Flügel",
      "Flughafen",
      "Flugzeug",
      "Fluid",
      "Flur",
      "Fluss",
      "Flüssigkeit",
      "Fokus",
      "Ford",
      "Form",
      "Forschung",
      "Fortschritt",
      "Foto",
      "Fotograf",
      "Fotografie",
      "Fracht",
      "Frage",
      "Fragment",
      "Franzosen",
      "Frau",
      "Freiheit",
      "Fremde",
      "Freude",
      "Freund",
      "Freundin",
      "Freundschaft",
      "Frieden",
      "Friedhof",
      "Fröhlichkeit",
      "Front",
      "Frosch",
      "Frost",
      "Frühling",
      "Frühstück",
      "Frustration",
      "Fuchs",
      "Führer",
      "Führung",
      "Fund",
      "Funke",
      "Funktion",
      "Fuß",
      "Fußball",
      "Gabel",
      "Gallerie",
      "Gang",
      "Gans",
      "Gänseblümchen",
      "Ganze",
      "Garage",
      "Gardine",
      "Garten",
      "Gas",
      "Gasse",
      "Gast",
      "Gastgeber",
      "Gasthaus",
      "Gate",
      "Gebäude",
      "Gebet",
      "Gebiet",
      "Gebrüll",
      "Geburt",
      "Geburtstag",
      "Gedächtnis",
      "Gedanke",
      "Gedicht",
      "Geduld",
      "Gefahr",
      "Gefangene",
      "Gefängnis",
      "Gefäss",
      "Gefolge",
      "Gefühl",
      "Gegenstand",
      "Geheimnis",
      "Gehen",
      "Gehirn",
      "Geist",
      "Gelächter",
      "Geländer",
      "Geld",
      "Geldbeutel",
      "Gelegenheit",
      "Geliebte",
      "Gemälde",
      "Gemeinde",
      "Gemüse",
      "Gen",
      "Generation",
      "Genie",
      "Gentleman",
      "Gerät",
      "Geräusch",
      "Gericht",
      "Geruch",
      "Gerücht",
      "Geschäft",
      "Geschäftsführer",
      "Geschenk",
      "Geschichte",
      "Geschlecht",
      "Geschmack",
      "Geschwindigkeit",
      "Gesellschaft",
      "Gesetz",
      "Gesicht",
      "Gespenst",
      "Gespräch",
      "Geste",
      "Gesundheit",
      "Getränk",
      "Getriebe",
      "Gewalt",
      "Gewebe",
      "Gewehr",
      "Gewicht",
      "Gezeiten",
      "Gift",
      "Gigant",
      "Gitarre",
      "Glas",
      "Glaube",
      "Glied",
      "Globus",
      "Glocke",
      "Glück",
      "Glühbirne",
      "Glühen",
      "Gnade",
      "Gold",
      "Golf",
      "Gott",
      "Gouverneur",
      "Grab",
      "Graben",
      "Grad",
      "Graf",
      "Gras",
      "Grat",
      "Graue",
      "Grenze",
      "Griff",
      "Grinsen",
      "Größe",
      "Großmutter",
      "Großvater",
      "Grube",
      "Grün",
      "Grund",
      "Grundlage",
      "Grunzen",
      "Gruppe",
      "Gummi",
      "Gunst",
      "Gurt",
      "Gürtel",
      "Gute",
      "Haar",
      "Habicht",
      "Hafen",
      "Hain",
      "Haken",
      "Hälfte",
      "Halle",
      "Hals",
      "Halskette",
      "Halt",
      "Hammer",
      "Hand",
      "Handel",
      "Handgelenk",
      "Händler",
      "Handlung",
      "Handschuh",
      "Handtuch",
      "Handvoll",
      "Handwerk",
      "Hank",
      "Hase",
      "Haube",
      "Haus",
      "Haushalt",
      "Hausschuh",
      "Haustier",
      "Haut",
      "Heap",
      "Heilige",
      "Held",
      "Helm",
      "Hemd",
      "Herausforderung",
      "Herbst",
      "Herd",
      "Herde",
      "Herr",
      "Herrlichkeit",
      "Herz",
      "Herzog",
      "Hexe",
      "Hilfe",
      "Himmel",
      "Hintergrund",
      "Hintern",
      "Hinweis",
      "Hirte",
      "Hitze",
      "Hochwasser",
      "Hochzeit",
      "Hof",
      "Hoffnung",
      "Höhe",
      "Höhle",
      "Hölle",
      "Holz",
      "Honig",
      "Horizont",
      "Horn",
      "Horror",
      "Hose",
      "Hosen",
      "Hotel",
      "Hubschrauber",
      "Hüfte",
      "Hügel",
      "Huhn",
      "Hülse",
      "Humor",
      "Hund",
      "Hunger",
      "Hure",
      "Hut",
      "Hütte",
      "Ich",
      "Idee",
      "Identität",
      "Idiot",
      "Illusion",
      "Impuls",
      "Information",
      "Ingenieur",
      "Inhalt",
      "Innenraum",
      "Insekt",
      "Insel",
      "Inspektor",
      "Instant",
      "Instinkt",
      "Instrument",
      "Intelligenz",
      "Intensität",
      "Interesse",
      "Internet",
      "Interview",
      "Iris",
      "Jacke",
      "Jagd",
      "Jäger",
      "Jahr",
      "Jahreszeit",
      "Jahrhundert",
      "Jahrzehnt",
      "Jeep",
      "Jugend",
      "Junge",
      "Jungfrau",
      "Justiz",
      "Juwel",
      "Kabel",
      "Kabinett",
      "Käfer",
      "Kaffee",
      "Käfig",
      "Kaiser",
      "Kajüte",
      "Kalb",
      "Kälte",
      "Kamera",
      "Kamin",
      "Kammer",
      "Kampagne",
      "Kampf",
      "Kämpfer",
      "Kanal",
      "Kapelle",
      "Kapital",
      "Kapitän",
      "Kapitel",
      "Kappe",
      "Karriere",
      "Karte",
      "Kartoffel",
      "Käse",
      "Katze",
      "Keks",
      "Keller",
      "Kellner",
      "Kellnerin",
      "Kerl",
      "Kern",
      "Kerze",
      "Kette",
      "Kiefer",
      "Kies",
      "Kind",
      "Kindheit",
      "Kinn",
      "Kirche",
      "Kirsche",
      "Kissen",
      "Kiste",
      "Kit",
      "Klang",
      "Klasse",
      "Klassenzimmer",
      "Klaue",
      "Klavier",
      "Kleid",
      "Kleider",
      "Kleidung",
      "Kleinkind",
      "Klick",
      "Klient",
      "Klinge",
      "Klinik",
      "Klippe",
      "Klopf",
      "Klumpen",
      "Knabe",
      "Knie",
      "Knöchel",
      "Knochen",
      "Knopf",
      "Knospe",
      "Knoten",
      "Koch",
      "Kochen",
      "Koffer",
      "Kofferraum",
      "Kohlen",
      "Koks",
      "Kollege",
      "Kolonie",
      "Kolumne",
      "Kombination",
      "Komfort",
      "Komitee",
      "Kommandant",
      "Kommentar",
      "Kommode",
      "Kommunikation",
      "Konferenz",
      "König",
      "Königin",
      "Königreich",
      "Können",
      "Konsequenz",
      "Konstruktion",
      "Kontakt",
      "Konto",
      "Kontrolle",
      "Konzentration",
      "Konzept",
      "Konzert",
      "Kopf",
      "Kopfnicken",
      "Kopfschmerz",
      "Kopie",
      "Korb",
      "Korn",
      "Körper",
      "Korridor",
      "Kosten",
      "Kostüm",
      "Kraft",
      "Kraftstoff",
      "Kragen",
      "Krähe",
      "Kran",
      "Krankenhaus",
      "Krankenschwester",
      "Krankenwagen",
      "Krankheit",
      "Kraut",
      "Kreation",
      "Kreatur",
      "Krebs",
      "Kredit",
      "Kreis",
      "Kreuz",
      "Krieg",
      "Krieger",
      "Krise",
      "Kristall",
      "Krone",
      "Küche",
      "Kuchen",
      "Kugel",
      "Kuh",
      "Kühlschrank",
      "Küken",
      "Kultur",
      "Kumpel",
      "Kunden",
      "Kunst",
      "Künstler",
      "Kunststoff",
      "Kupfer",
      "Kuppel",
      "Kurs",
      "Kurve",
      "Kuss",
      "Küste",
      "Labor",
      "Lächeln",
      "Lachen",
      "Ladung",
      "Lamm",
      "Lampe",
      "Land",
      "Landschaft",
      "Landung",
      "Länge",
      "Lappen",
      "Last",
      "Laterne",
      "Lauf",
      "Lautsprecher",
      "Leben",
      "Lebenden",
      "Lebensdauer",
      "Lebensmittel",
      "Leder",
      "Legende",
      "Lehrer",
      "Leiche",
      "Leichtigkeit",
      "Leidenschaft",
      "Leinen",
      "Leinwand",
      "Leiste",
      "Leistung",
      "Leiter",
      "Lesen",
      "Leser",
      "Leutnant",
      "Level",
      "Licht",
      "Liebe",
      "Liebhaber",
      "Liebling",
      "Lied",
      "Lieferung",
      "Lift",
      "Liga",
      "Limit",
      "Linie",
      "Link",
      "Linse",
      "Lippe",
      "Lippenstift",
      "Liste",
      "Literatur",
      "Lizenz",
      "Lobby",
      "Loch",
      "Locke",
      "Löffel",
      "Lorbeer",
      "Lösung",
      "Löwe",
      "Lücke",
      "Luft",
      "Lüge",
      "Luke",
      "Lunge",
      "Macht",
      "Madame",
      "Mädchen",
      "Magazin",
      "Magie",
      "Mahlzeit",
      "Mais",
      "Makeup",
      "Maler",
      "Mama",
      "Mangel",
      "Mann",
      "Mannschaft",
      "Manschette",
      "Mantel",
      "Märchen",
      "Marine",
      "Marke",
      "Markt",
      "Marmor",
      "Marsch",
      "Maschine",
      "Maske",
      "Maß",
      "Masse",
      "Material",
      "Mathematik",
      "Matratze",
      "Matte",
      "Mauer",
      "Maultier",
      "Maurer",
      "Maus",
      "Maximum",
      "Medien",
      "Medikament",
      "Medizin",
      "Meer",
      "Meinung",
      "Meister",
      "Melodie",
      "Menge",
      "Mensch",
      "Menschlichkeit",
      "Menü",
      "Messer",
      "Messestand",
      "Messgerät",
      "Messing",
      "Metall",
      "Methode",
      "Metzger",
      "Miete",
      "Milch",
      "Mine",
      "Minister",
      "Minute",
      "Mission",
      "Mist",
      "Mitglied",
      "Mitleid",
      "Mittag",
      "Mittagessen",
      "Mitte",
      "Mitternacht",
      "Möbel",
      "Mode",
      "Model",
      "Möglichkeit",
      "Moment",
      "Momma",
      "Monat",
      "Mönch",
      "Mond",
      "Mondlicht",
      "Monster",
      "Mord",
      "Mörder",
      "Morgen",
      "Morgendämmerung",
      "Motel",
      "Motor",
      "Mühle",
      "Müll",
      "Müller",
      "Mund",
      "Mündel",
      "Münze",
      "Muschel",
      "Museum",
      "Musik",
      "Musiker",
      "Muskel",
      "Muster",
      "Mut",
      "Mutter",
      "Mysterium",
      "Nachbar",
      "Nachbarschaft",
      "Nachfrage",
      "Nachmittag",
      "Nachricht",
      "Nachrichten",
      "Nacht",
      "Nadel",
      "Nagel",
      "Name",
      "Narbe",
      "Nase",
      "Nasenloch",
      "Nation",
      "Natur",
      "Nebel",
      "Neigung",
      "Nerv",
      "Nest",
      "Netz",
      "Netzwerk",
      "Neugier",
      "Nonne",
      "Nord",
      "Note",
      "Notebook",
      "Notfall",
      "Notiz",
      "Oberfläche",
      "Oberschenkel",
      "Oberst",
      "Objekt",
      "Obst",
      "Öffentlichkeit",
      "Offizielle",
      "Offizier",
      "Ohr",
      "Ohrring",
      "Öl",
      "Oma",
      "Onkel",
      "Opa",
      "Oper",
      "Operation",
      "Opfer",
      "Option",
      "Orange",
      "Organisation",
      "Orgel",
      "Ort",
      "Osten",
      "Outfit",
      "Ozean",
      "Paar",
      "Paket",
      "Palast",
      "Palme",
      "Panik",
      "Panzer",
      "Papa",
      "Papier",
      "Parade",
      "Parfüm",
      "Park",
      "Partner",
      "Party",
      "Pass",
      "Passagier",
      "Pat",
      "Patch",
      "Patient",
      "Patrouille",
      "Patty",
      "Pause",
      "Periode",
      "Perle",
      "Person",
      "Personal",
      "Persönlichkeit",
      "Pfad",
      "Pfanne",
      "Pfarrer",
      "Pfeife",
      "Pfeil",
      "Pferd",
      "Pflanze",
      "Pflege",
      "Pflicht",
      "Pfote",
      "Pfund",
      "Phantasie",
      "Picknick",
      "Pier",
      "Pille",
      "Pilot",
      "Pinsel",
      "Pirat",
      "Piste",
      "Pistole",
      "Pizza",
      "Plakat",
      "Plan",
      "Planet",
      "Platform",
      "Platte",
      "Platz",
      "Pochen",
      "Poesie",
      "Poet",
      "Pol",
      "Politik",
      "Polizei",
      "Polizist",
      "Pop",
      "Portion",
      "Porträt",
      "Position",
      "Post",
      "Präsident",
      "Prediger",
      "Preis",
      "Presse",
      "Priester",
      "Prinz",
      "Prinzessin",
      "Prinzip",
      "Privatsphäre",
      "Problem",
      "Produkt",
      "Produktion",
      "Professor",
      "Profil",
      "Programm",
      "Projekt",
      "Prospekt",
      "Protest",
      "Protokoll",
      "Prozess",
      "Prüfung",
      "Publikum",
      "Puff",
      "Pullover",
      "Pulver",
      "Pumpe",
      "Punkt",
      "Punktzahl",
      "Puppe",
      "Quadrat",
      "Qualität",
      "Quelle",
      "Rabbi",
      "Rad",
      "Radio",
      "Rahmen",
      "Rakete",
      "Rampe",
      "Ranch",
      "Rand",
      "Rang",
      "Rasen",
      "Rast",
      "Rat",
      "Rate",
      "Ratgeber",
      "Ratschlag",
      "Ratte",
      "Rauch",
      "Raum",
      "Reaktion",
      "Realität",
      "Rechnung",
      "Recht",
      "Rede",
      "Reed",
      "Referenz",
      "Reflexion",
      "Regal",
      "Regel",
      "Regen",
      "Regenschirm",
      "Regierung",
      "Region",
      "Reh",
      "Reich",
      "Reichtum",
      "Reichweite",
      "Reihe",
      "Reis",
      "Reise",
      "Reisende",
      "Reiß",
      "Relative",
      "Relief",
      "Religion",
      "Rennen",
      "Reporter",
      "Respekt",
      "Ressource",
      "Restaurant",
      "Rezeption",
      "Rhythmus",
      "Richter",
      "Richtlinie",
      "Richtung",
      "Ring",
      "Rippe",
      "Risiko",
      "Riss",
      "Ritter",
      "Ritual",
      "Robe",
      "Roboter",
      "Rock",
      "Rohr",
      "Rolle",
      "Rollstuhl",
      "Roman",
      "Romantik",
      "Rose",
      "Rotkehlchen",
      "Route",
      "Routine",
      "Rubin",
      "Rück",
      "Rücken",
      "Rückkehr",
      "Rucksack",
      "Rudel",
      "Ruf",
      "Ruhe",
      "Ruine",
      "Rumpf",
      "Runde",
      "Runden",
      "Rüstung",
      "Rutsche",
      "Saat",
      "Sack",
      "Saft",
      "Salat",
      "Salz",
      "Sammlung",
      "Samt",
      "Sand",
      "Sandwich",
      "Sänger",
      "Sarg",
      "Satellit",
      "Sattel",
      "Satz",
      "Sauce",
      "Sauerstoff",
      "Schädel",
      "Schaden",
      "Schaf",
      "Schal",
      "Schale",
      "Schalter",
      "Schande",
      "Schatten",
      "Schattierung",
      "Schatz",
      "Schaufel",
      "Schaukel",
      "Schauspieler",
      "Schauspielerin",
      "Scheibe",
      "Scheidung",
      "Scheinwerfer",
      "Scheune",
      "Schicht",
      "Schicksal",
      "Schiene",
      "Schiff",
      "Schild",
      "Schildkröte",
      "Schlaf",
      "Schlafanzüge",
      "Schlafzimmer",
      "Schlag",
      "Schlamm",
      "Schlange",
      "Schlauch",
      "Schleife",
      "Schließfach",
      "Schloss",
      "Schlucht",
      "Schlüssel",
      "Schmerz",
      "Schmetterling",
      "Schmuck",
      "Schnee",
      "Schnitt",
      "Schnur",
      "Schnurrbart",
      "Schock",
      "Schokolade",
      "Schönheit",
      "Schrank",
      "Schrecken",
      "Schrei",
      "Schreiben",
      "Schreibtisch",
      "Schritt",
      "Schrotflinte",
      "Schrott",
      "Schublade",
      "Schuh",
      "Schuld",
      "Schule",
      "Schüler",
      "Schulter",
      "Schuppen",
      "Schürze",
      "Schuss",
      "Schutz",
      "Schwäche",
      "Schwarze",
      "Schweif",
      "Schwein",
      "Schweiß",
      "Schwerkraft",
      "Schwert",
      "Schwester",
      "Schwierigkeit",
      "Schwierigkeiten",
      "Schwimmbecken",
      "Schwimmen",
      "See",
      "Seele",
      "Seemann",
      "Segen",
      "Sehenswürdigkeit",
      "Seide",
      "Seife",
      "Seil",
      "Sein",
      "Seite",
      "Seitenleiste",
      "Sekretär",
      "Sektion",
      "Selbstmord",
      "Senator",
      "Sensation",
      "Sequenz",
      "Service",
      "Serviette",
      "Seufzer",
      "Sicherheit",
      "Sicht",
      "Sieg",
      "Sieger",
      "Signal",
      "Silber",
      "Sinn",
      "Sirene",
      "Situation",
      "Sitzung",
      "Skala",
      "Skelett",
      "Skript",
      "Slave",
      "Socke",
      "Soda",
      "Sofa",
      "Sohn",
      "Soldat",
      "Sommer",
      "Sonne",
      "Sonnenbrille",
      "Sonnenlicht",
      "Sonnenschein",
      "Sonnenuntergang",
      "Sorge",
      "Spannfutter",
      "Spannung",
      "Spaß",
      "Speer",
      "Speicher",
      "Speisesaal",
      "Spiegel",
      "Spiel",
      "Spieler",
      "Spielzeug",
      "Spinne",
      "Spitze",
      "Spitzer",
      "Sport",
      "Sprache",
      "Spray",
      "Spur",
      "Staat",
      "Stadt",
      "Stahl",
      "Stall",
      "Stamm",
      "Stand",
      "Standard",
      "Ständige",
      "Standort",
      "Stange",
      "Stapel",
      "Star",
      "Stare",
      "Stärke",
      "Statue",
      "Status",
      "Staub",
      "Steak",
      "Stein",
      "Stellvertretende",
      "Stern",
      "Steuer",
      "Steuermann",
      "Stift",
      "Stil",
      "Stille",
      "Stimme",
      "Stimmung",
      "Stirn",
      "Stirnrunzeln",
      "Stock",
      "Stolz",
      "Strafe",
      "Strahl",
      "Strand",
      "Strang",
      "Straße",
      "Strecke",
      "Streifen",
      "Strohhalm",
      "Strom",
      "Strömung",
      "Struktur",
      "Stück",
      "Studie",
      "Studio",
      "Studium",
      "Stuhl",
      "Stumpf",
      "Stunde",
      "Stundenplan",
      "Sturm",
      "Suche",
      "Süden",
      "Suite",
      "Summe",
      "Sumpf",
      "Sünde",
      "Suppe",
      "Süßigkeit",
      "Symbol",
      "Sympathie",
      "System",
      "Szene",
      "Tabak",
      "Tafel",
      "Tag",
      "Tagebuch",
      "Tageslicht",
      "Taille",
      "Tal",
      "Talent",
      "Tante",
      "Tanz",
      "Tanzen",
      "Tänzerin",
      "Tasche",
      "Taschenlampe",
      "Taschentuch",
      "Tasse",
      "Tätowierung",
      "Tatsache",
      "Taube",
      "Taxi",
      "Team",
      "Techniker",
      "Technologie",
      "Tee",
      "Teenager",
      "Teich",
      "Teil",
      "Teilen",
      "Telefon",
      "Teller",
      "Tempel",
      "Temperatur",
      "Tennis",
      "Teppich",
      "Termin",
      "Terrasse",
      "Territorium",
      "Test",
      "Teufel",
      "Text",
      "Theater",
      "Thema",
      "Theorie",
      "Ticket",
      "Tiefe",
      "Tier",
      "Tiger",
      "Tinten",
      "Tisch",
      "Titel",
      "Titelseite",
      "Toast",
      "Tochter",
      "Tod",
      "Toilette",
      "Tomate",
      "Ton",
      "Tonhöhe",
      "Topf",
      "Töten",
      "Tourist",
      "Tradition",
      "Tragödie",
      "Trainer",
      "Training",
      "Trauer",
      "Traum",
      "Traurigkeit",
      "Treffen",
      "Treppen",
      "Treppenhaus",
      "Trick",
      "Trikot",
      "Trink",
      "Trinkgeld",
      "Tritt",
      "Trommel",
      "Trübung",
      "Trümmer",
      "Truppe",
      "Truthahn",
      "Tunnel",
      "Tür",
      "Turm",
      "Türöffnung",
      "Typ",
      "Überprüfung",
      "Überraschung",
      "Übung",
      "Uhr",
      "Umarmung",
      "Umgebung",
      "Umhang",
      "Umlaufbahn",
      "Umschlag",
      "Umstand",
      "Unfall",
      "Unglaube",
      "Unglück",
      "Uniform",
      "Union",
      "Universität",
      "Universum",
      "Unkraut",
      "Unordnung",
      "Unsinn",
      "Unterarm",
      "Unterhaltung",
      "Unternehmen",
      "Unterricht",
      "Unterschied",
      "Unterstützung",
      "Unterwäsche",
      "Urlaub",
      "Ursprung",
      "Urteil",
      "Vampir",
      "Vater",
      "Vene",
      "Verantwortung",
      "Verbindung",
      "Verbrechen",
      "Verdacht",
      "Vereinbarung",
      "Verfahren",
      "Verfasser",
      "Vergangenheit",
      "Vergnügungspark",
      "Verhalten",
      "Verhältnis",
      "Verkauf",
      "Verkehr",
      "Verlangen",
      "Verlegenheit",
      "Verletzung",
      "Verlust",
      "Vermutung",
      "Versagen",
      "Versammlung",
      "Verschiebung",
      "Versicherung",
      "Version",
      "Versorgung",
      "Versprechen",
      "Verständnis",
      "Versuch",
      "Verteidigung",
      "Vertrag",
      "Vertrauen",
      "Verwendung",
      "Verwirrung",
      "Verzweiflung",
      "Video",
      "Vieh",
      "Vielfalt",
      "Viertel",
      "Villa",
      "Violett",
      "Vogel",
      "Volk",
      "Volumen",
      "Vorabend",
      "Vorfahr",
      "Vorfall",
      "Vorhalle",
      "Vorhandensein",
      "Vormarsch",
      "Vorschlag",
      "Vorstellung",
      "Vorteil",
      "Vortrag",
      "Wächter",
      "Wachtmeister",
      "Waffe",
      "Wagen",
      "Wahl",
      "Wahrheit",
      "Wal",
      "Wald",
      "Wanderer",
      "Wandern",
      "Wange",
      "Wanne",
      "Warenhaus",
      "Wärme",
      "Warnung",
      "Warte",
      "Waschbecken",
      "Wäsche",
      "Wasser",
      "Wasserhahn",
      "Wechsel",
      "Wecker",
      "Weg",
      "Weibchen",
      "Weihnachtslied",
      "Wein",
      "Weinen",
      "Weinstock",
      "Weisheit",
      "Weiß",
      "Welle",
      "Welpe",
      "Welt",
      "Wende",
      "Werkzeug",
      "Wert",
      "Westen",
      "Wetter",
      "Wiedersehen",
      "Wiese",
      "Wille",
      "Wind",
      "Windschutzscheibe",
      "Winkel",
      "Winter",
      "Wirbelsäule",
      "Wissen",
      "Wissenschaft",
      "Wissenschaftler",
      "Witwe",
      "Witz",
      "Woche",
      "Wochenende",
      "Wohl",
      "Wohnung",
      "Wohnzimmer",
      "Wolf",
      "Wolke",
      "Wolle",
      "Wort",
      "Wulst",
      "Wunde",
      "Wunder",
      "Wunsch",
      "Würfel",
      "Wurm",
      "Wüste",
      "Wut",
      "Zähler",
      "Zahlung",
      "Zählung",
      "Zahn",
      "Zauber",
      "Zauberer",
      "Zaun",
      "Zehe",
      "Zeichnung",
      "Zeit",
      "Zeitung",
      "Zelle",
      "Zelt",
      "Zentrum",
      "Zeremonie",
      "Zeug",
      "Zeuge",
      "Ziege",
      "Ziegel",
      "Ziel",
      "Zifferblatt",
      "Zigarette",
      "Zigarre",
      "Zimmer",
      "Zivilisation",
      "Zone",
      "Zucker",
      "Zuflucht",
      "Zufriedenheit",
      "Zug",
      "Zugehörigkeit",
      "Zugriff",
      "Zuhause",
      "Zukunft",
      "Zunge",
      "Zuordnung",
      "Zuschuss",
      "Zweifel",
      "Zweite",
      "Zwielicht",
      "Zwilling"
    ]
  },
  "landforms": {
    "name": "Landforms",
    "source": "https://en.wikipedia.org/wiki/List_of_landforms",
    "values": [
      "Abîme",
      "Abyssal fan",
      "Abyssal plain",
      "Ait",
      "Alluvial fan",
      "Anabranch",
      "Arch",
      "Archipelago",
      "Arête",
      "Arroyo",
      "Asymmetric valley",
      "Atoll",
      "Ayre",
      "Backswamp",
      "Badlands",
      "Bar",
      "Barrier bar",
      "Barrier island",
      "Bay",
      "Baymouth bar",
      "Bayou",
      "Beach",
      "Beach cusps",
      "Beach ridge",
      "Bench",
      "Bight",
      "Blowhole",
      "Bluff",
      "Bornhardt",
      "Braided channel",
      "Braided river",
      "Butte",
      "Calanque",
      "Caldera",
      "Canyon",
      "Cape",
      "Carolina bay",
      "Cave",
      "Cenote",
      "Central peak",
      "Channel",
      "Cinder cone",
      "Cirque",
      "Cliff",
      "Coast",
      "Col",
      "Complex crater",
      "Complex volcano",
      "Confluence",
      "Continental shelf",
      "Coral reef",
      "Corrie",
      "Cove",
      "Cratered landscape",
      "Crevasse",
      "Crevasse splay",
      "Cryoplanation",
      "Cryoplanation terrace",
      "Cryovolcano",
      "Cryptodome",
      "Cuesta",
      "Cuspate foreland",
      "Cut bank",
      "Dale",
      "Defile",
      "Dell",
      "Diatreme",
      "Dike",
      "Dirt cone",
      "Dissected plateau",
      "Doab",
      "Dome",
      "Drainage basin",
      "Drainage basin",
      "Drainage divide",
      "Draw",
      "Drumlin",
      "Dry lake",
      "Dune",
      "Dune system",
      "Earth hummocks",
      "Ejecta blanket",
      "Endorheic basin",
      "Entrenched meander",
      "Epigenetic valley",
      "Erg",
      "Escarpment",
      "Esker",
      "Estuary",
      "Etchplain",
      "Exhumed river channel",
      "Faceted spur",
      "Fault scarp",
      "Firth",
      "Fissure vent",
      "Fjord",
      "Flared slope",
      "Flat",
      "Flatiron",
      "Floodplain",
      "Flute",
      "Fluting",
      "Fluvial island",
      "Fluvial terrace",
      "Flyggberg",
      "Foiba",
      "Geo",
      "Geyser",
      "Glacial horn",
      "Glacier",
      "Glacier cave",
      "Glacier foreland",
      "Glen",
      "Gorge",
      "Graben",
      "Gulch",
      "Gulf",
      "Gully",
      "Guyot",
      "Hanging valley",
      "Headland",
      "High island",
      "Hill",
      "Hillock",
      "Hogback",
      "Homoclinal ridge",
      "Honeycomb weathering",
      "Hoodoo",
      "Hornito",
      "Horst",
      "Impact crater",
      "Impact crater lake",
      "Inlet",
      "Inselberg",
      "Interfluve",
      "Inverted relief",
      "Island",
      "Islet",
      "Isthmus",
      "Kame",
      "Kame delta",
      "Karst",
      "Karst fenster",
      "Kettle",
      "Kīpuka",
      "Knoll",
      "Lacustrine plain",
      "Lacustrine terraces",
      "Lagoon",
      "Lake",
      "Lava",
      "Lava coulee",
      "Lava dome",
      "Lava dome",
      "Lava dome",
      "Lava field",
      "Lava lake",
      "Lava plain",
      "Lava spine",
      "Lava tube",
      "Lavaka",
      "Levee",
      "Limestone pavement",
      "List of rock formations",
      "Lithalsa",
      "Maar",
      "Machair",
      "Malpaís",
      "Mamelon",
      "Marine terrace",
      "Marsh",
      "Meander",
      "Mesa",
      "Mid-ocean ridge",
      "Misfit stream",
      "Mogote",
      "Monadnock",
      "Moraine",
      "Moulin",
      "Mountain",
      "Mountain pass",
      "Mountain pass",
      "Mountain range",
      "Mud volcano",
      "Mushroom rock",
      "Natural arch",
      "Nivation",
      "Nivation hollow",
      "Nubbin",
      "Nunatak",
      "Oasis",
      "Oceanic basin",
      "Oceanic plateau",
      "Oceanic ridge",
      "Oceanic trench",
      "Outwash fan",
      "Outwash plain",
      "Oxbow lake",
      "Paleoplain",
      "Paleosurface",
      "Palsa",
      "Panhole",
      "Pediment",
      "Pediplain",
      "Peneplain",
      "Peninsula",
      "Permafrost plateau",
      "Pingo",
      "Pit crater",
      "Plain",
      "Planation surface",
      "Plateau",
      "Plunge pool",
      "Point bar",
      "Polje",
      "Pond",
      "Potrero",
      "Pounus",
      "Proglacial lake",
      "Pseudocrater",
      "Pull-apart basin",
      "Pyramidal peak",
      "Pyroclastic shield",
      "Raised beach",
      "Rapid",
      "Ravine",
      "Resurgent dome",
      "Ria",
      "Ribbed moraines",
      "Ridge",
      "Riffle",
      "Rift valley",
      "River",
      "River delta",
      "River island",
      "River valley",
      "Rôche moutonnée",
      "Rock glacier",
      "Rock shelter",
      "Rock-cut basin",
      "Rogen moraine",
      "Rootless cone",
      "Saddle",
      "Salt flat",
      "Salt marsh",
      "Salt pan",
      "Sand boil",
      "Sandur",
      "Scarp",
      "Scowle",
      "Scree",
      "Sea cave",
      "Seamount",
      "Seamount chains",
      "Shield volcano",
      "Shoal",
      "Shore",
      "Shut-in",
      "Side valley",
      "Simple crater",
      "Sinkhole",
      "Solifluction lobes and sheets",
      "Somma volcano",
      "Sound",
      "Spatter cone",
      "Spit",
      "Spring",
      "Stack",
      "Strait",
      "Strandflat",
      "Strath",
      "Stratovolcano",
      "Stream",
      "Stream pool",
      "Strike ridge",
      "Structural bench",
      "Structural terrace",
      "Subglacial mound",
      "Submarine canyon",
      "Submarine volcano",
      "Summit",
      "Supervolcano",
      "Surge channel",
      "Swamp",
      "Tafoni",
      "Tepui",
      "Terrace",
      "Terracette",
      "Tessellated pavement",
      "Thalweg",
      "Thermokarst",
      "Tidal marsh",
      "Tide pool",
      "Tombolo",
      "Tor",
      "Towhead",
      "Trim line",
      "Truncated spur",
      "Tuff cone",
      "Tunnel valley",
      "Turlough",
      "Tuya",
      "U-shaped valley",
      "Uvala",
      "V-shaped valley",
      "Vale",
      "Valley",
      "Valley shoulder",
      "Volcanic arc",
      "Volcanic cone",
      "Volcanic crater",
      "Volcanic crater lake",
      "Volcanic dam",
      "Volcanic field",
      "Volcanic group",
      "Volcanic island",
      "Volcanic plateau",
      "Volcanic plug",
      "Volcanic vent",
      "Volcano",
      "Wadi",
      "Waterfall",
      "Watershed",
      "Wave-cut platform",
      "Yazoo stream"
    ]
  },
  "adjectives_en": {
    "name": "English Adjectives",
    "source": "https://grammar.yourdictionary.com/parts-of-speech/adjectives/list-of-adjective-words.html",
    "values": [
      "Adorable",
      "Adventurous",
      "Aggressive",
      "Agreeable",
      "Alert",
      "Alive",
      "Amused",
      "Angry",
      "Annoyed",
      "Annoying",
      "Anxious",
      "Arrogant",
      "Ashamed",
      "Attractive",
      "Average",
      "Awful",
      "Bad",
      "Beautiful",
      "Better",
      "Bewildered",
      "Black",
      "Bloody",
      "Blue-eyed",
      "Blue",
      "Blushing",
      "Bored",
      "Brainy",
      "Brave",
      "Breakable",
      "Bright",
      "Busy",
      "Calm",
      "Careful",
      "Cautious",
      "Charming",
      "Cheerful",
      "Clean",
      "Clear",
      "Clever",
      "Cloudy",
      "Clumsy",
      "Colorful",
      "Combative",
      "Comfortable",
      "Concerned",
      "Condemned",
      "Confused",
      "Cooperative",
      "Courageous",
      "Crazy",
      "Creepy",
      "Crowded",
      "Cruel",
      "Curious",
      "Cute",
      "Dangerous",
      "Dark",
      "Dead",
      "Defeated",
      "Defiant",
      "Delightful",
      "Depressed",
      "Determined",
      "Different",
      "Difficult",
      "Disgusted",
      "Distinct",
      "Disturbed",
      "Dizzy",
      "Doubtful",
      "Drab",
      "Dull",
      "Eager",
      "Easy",
      "Elated",
      "Elegant",
      "Embarrassed",
      "Enchanting",
      "Encouraging",
      "Energetic",
      "Enthusiastic",
      "Envious",
      "Evil",
      "Excited",
      "Expensive",
      "Exuberant",
      "Fair",
      "Faithful",
      "Famous",
      "Fancy",
      "Fantastic",
      "Fierce",
      "Filthy",
      "Fine",
      "Foolish",
      "Fragile",
      "Frail",
      "Frantic",
      "Friendly",
      "Frightened",
      "Funny",
      "Gentle",
      "Gifted",
      "Glamorous",
      "Gleaming",
      "Glorious",
      "Good",
      "Gorgeous",
      "Graceful",
      "Grieving",
      "Grotesque",
      "Grumpy",
      "Handsome",
      "Happy",
      "Healthy",
      "Helpful",
      "Helpless",
      "Hilarious",
      "Homeless",
      "Homely",
      "Horrible",
      "Hungry",
      "Hurt",
      "Ill",
      "Important",
      "Impossible",
      "Inexpensive",
      "Innocent",
      "Inquisitive",
      "Itchy",
      "Jealous",
      "Jittery",
      "Jolly",
      "Joyous",
      "Kind",
      "Lazy",
      "Light",
      "Lively",
      "Lonely",
      "Long",
      "Lovely",
      "Lucky",
      "Magnificent",
      "Misty",
      "Modern",
      "Motionless",
      "Muddy",
      "Mushy",
      "Mysterious",
      "Nasty",
      "Naughty",
      "Nervous",
      "Nice",
      "Nutty",
      "Obedient",
      "Obnoxious",
      "Odd",
      "Old-fashioned",
      "Open",
      "Outrageous",
      "Outstanding",
      "Panicky",
      "Perfect",
      "Plain",
      "Pleasant",
      "Poised",
      "Poor",
      "Powerful",
      "Precious",
      "Prickly",
      "Proud",
      "Putrid",
      "Puzzled",
      "Quaint",
      "Real",
      "Relieved",
      "Repulsive",
      "Rich",
      "Scary",
      "Selfish",
      "Shiny",
      "Shy",
      "Silly",
      "Sleepy",
      "Smiling",
      "Smoggy",
      "Sore",
      "Sparkling",
      "Splendid",
      "Spotless",
      "Stormy",
      "Strange",
      "Stupid",
      "Successful",
      "Super",
      "Talented",
      "Tame",
      "Tasty",
      "Tender",
      "Tense",
      "Terrible",
      "Thankful",
      "Thoughtful",
      "Thoughtless",
      "Tired",
      "Tough",
      "Troubled",
      "Ugliest",
      "Ugly",
      "Uninterested",
      "Unsightly",
      "Unusual",
      "Upset",
      "Uptight",
      "Vast",
      "Victorious",
      "Vivacious",
      "Wandering",
      "Weary",
      "Wicked",
      "Wide-eyed",
      "Wild",
      "Witty",
      "Worried",
      "Worrisome",
      "Wrong",
      "Zany",
      "Zealous"
    ]
  },
  "gemstones": {
    "name": "Gemstones",
    "source": "https://www.gemsociety.org/gemstone-encyclopedia/",
    "values": [
      "Actinolite",
      "Adamite",
      "Agate",
      "Albite",
      "Alexandrite",
      "Algodonite",
      "Almandine Garnet",
      "Amazonite",
      "Amber",
      "Amblygonite",
      "Amethyst",
      "Ametrine",
      "Ammolite",
      "Analcime",
      "Anatase",
      "Andalusite",
      "Andesine",
      "Andradite",
      "Anglesite",
      "Anhydrite (Angelite)",
      "Anorthite",
      "Apatite",
      "Apophyllite",
      "Aquamarine",
      "Aragonite",
      "Augelite",
      "Axinite",
      "Azurite",
      "Barite",
      "Bayldonite",
      "Benitoite",
      "Beryl",
      "Beryllonite",
      "Bismutotantalite",
      "Bloodstone",
      "Boleite",
      "Boracite",
      "Bornite",
      "Brazilianite",
      "Breithauptite",
      "Brookite",
      "Brucite",
      "Bustamite",
      "Bytownite",
      "Calcareous Concretions",
      "Calcite",
      "Canasite",
      "Cancrinite",
      "Carnelian",
      "Cassiterite",
      "Catapleiite",
      "Celestite",
      "Ceruleite",
      "Cerussite",
      "Chabazite",
      "Chalcedony",
      "Chambersite",
      "Charoite",
      "Chicken-Blood Stone",
      "Childrenite",
      "Chiolite",
      "Chromite",
      "Chrysoberyl",
      "Chrysocolla",
      "Chrysocolla Chalcedony",
      "Chrysoprase",
      "Cinnabar",
      "Citrine",
      "Clinochlore",
      "Cobaltite",
      "Colemanite",
      "Color Change Garnet",
      "Color Change Sapphire",
      "Coral",
      "Cordierite",
      "Corundum",
      "Covellite",
      "Creedite",
      "Crocoite",
      "Cryolite",
      "Cuprite",
      "Danburite",
      "Datolite",
      "Demantoid Garnet",
      "Diamond",
      "Diaspore",
      "Dickinsonite",
      "Diopside",
      "Dioptase",
      "Dolomite",
      "Dumortierite",
      "Ekanite",
      "Emerald",
      "Enstatite",
      "Eosphorite",
      "Epidote",
      "Ettringite",
      "Euclase",
      "Eudialyte",
      "Euxenite",
      "Feldspar",
      "Fergusonite",
      "Fluorite",
      "Fossilized Organisms",
      "Freshwater Pearl",
      "Friedelite",
      "Gadolinite",
      "Gahnospinel",
      "Garnet",
      "Gaylussite",
      "Glass",
      "Grandidierite",
      "Grossular Garnet",
      "Gypsum",
      "Hambergite",
      "Haüyne",
      "Heliodor",
      "Hematite",
      "Hemimorphite",
      "Herderite",
      "Hessonite",
      "Hodgkinsonite",
      "Holtite",
      "Howlite",
      "Huebnerite (Hübnerite)",
      "Humite",
      "Hureaulite",
      "Hurlbutite",
      "Hydrogrossular Garnet",
      "Idocrase (Vesuvianite)",
      "Inderite",
      "Iolite",
      "Jadeite",
      "Jasper",
      "Jeremejevite",
      "Jet",
      "Kämmererite",
      "Kornerupine",
      "Kurnakovite",
      "Kyanite",
      "Labradorite",
      "Langbeinite",
      "Lapis Lazuli",
      "Laserblue",
      "Lawsonite",
      "Lazulite",
      "Legrandite",
      "Lepidolite",
      "Leucite",
      "Linarite",
      "Ludlamite",
      "Magnesite",
      "Malachite",
      "Malaia Garnet (Malaya Garnet)",
      "Mali Garnet",
      "Mandarin Garnet",
      "Manganotantalite",
      "Marcasite",
      "Meliphanite",
      "Mellite",
      "Microcline",
      "Microlite",
      "Milarite",
      "Millerite",
      "Mimetite",
      "Moldavite",
      "Monazite",
      "Moonstone",
      "Mordenite",
      "Morganite",
      "Nambulite",
      "Natrolite, Mesolite, Scolecite",
      "Natural Glass",
      "Nepheline",
      "Nephrite",
      "Neptunite",
      "Niccolite (Nickeline)",
      "Obsidian",
      "Oligoclase",
      "Onyx",
      "Opal",
      "Oregon Sunstone",
      "Orthoclase",
      "Padparadscha Sapphire",
      "Painite",
      "Palygorskite",
      "Papagoite",
      "Paraíba Tourmaline",
      "Pargasite",
      "Parisite",
      "Pearl",
      "Pectolite (Larimar)",
      "Pentlandite",
      "Periclase",
      "Peridot",
      "Peristerite",
      "Perthite",
      "Petalite",
      "Phenakite",
      "Phosgenite",
      "Phosphophyllite",
      "Pollucite",
      "Powellite",
      "Prehnite",
      "Prosopite",
      "Proteus",
      "Proustite",
      "Pumpellyite",
      "Purpurite",
      "Pyrargyrite",
      "Pyrite",
      "Pyrope Garnet",
      "Pyrophyllite",
      "Pyroxmangite",
      "Pyrrhotite",
      "Quartz",
      "Quartzite",
      "Realgar",
      "Red Beryl",
      "Rhodizite",
      "Rhodochrosite",
      "Rhodolite Garnet",
      "Rhodonite",
      "Rose Quartz",
      "Rubellite",
      "Ruby",
      "Rutile",
      "Saltwater Pearl",
      "Samarskite",
      "Sanidine",
      "Sapphire",
      "Sapphirine",
      "Sarcolite",
      "Scapolite",
      "Scheelite",
      "Scorodite",
      "Sellaite",
      "Senarmontite",
      "Serandite",
      "Serpentine",
      "Shattuckite",
      "Shell (Sea Shells)",
      "Shortite",
      "Siderite",
      "Sillimanite",
      "Simpsonite",
      "Sinhalite",
      "Smaltite",
      "Smithsonite",
      "Smoky Quartz",
      "Sodalite",
      "Sogdianite",
      "Spessartite Garnet",
      "Sphalerite",
      "Sphene (Titanite)",
      "Spinel",
      "Spodumene",
      "Spurrite",
      "Star Sapphire",
      "Staurolite",
      "Stibiotantalite",
      "Stichtite",
      "Stolzite",
      "Strontianite",
      "Sugilite",
      "Sulfur (Sulphur)",
      "Sunstone",
      "Taaffeite",
      "Talc",
      "Tantalite",
      "Tanzanite (Zoisite)",
      "Tektite",
      "Tephroite",
      "Thaumasite",
      "Thomsonite",
      "Tiger's Eye",
      "Topaz",
      "Tourmaline",
      "Tremolite",
      "Triphylite (Tryphylite)",
      "Tsavorite Garnet",
      "Tugtupite",
      "Turquoise",
      "Ulexite",
      "Uvarovite Garnet",
      "Vanadinite",
      "Variscite",
      "Väyrynenite",
      "Villiaumite",
      "Vivianite",
      "Wardite",
      "Wavellite",
      "Weloganite",
      "Whewellite",
      "Wilkeite",
      "Willemite",
      "Witherite",
      "Wollastonite",
      "Wulfenite",
      "Xonotlite",
      "Yugawaralite",
      "Zektzerite",
      "Zincite",
      "Zircon",
      "Zunyite"
    ]
  }
};
