var categories = {
  "si_prefixes": {
    "name": "SI Prefixes",
    "values": [
      "yotta",
      "zetta",
      "exa",
      "peta",
      "tera",
      "giga",
      "mega",
      "kilo",
      "hecto",
      "deca",
      "deci",
      "centi",
      "milli",
      "micro",
      "nano",
      "pico",
      "femto",
      "atto",
      "zepto",
      "yocto"
    ]
  },
  "elements": {
    "name": "Chemical Elements",
    "values": [
      "Hydrogen",
      "Helium",
      "Lithium",
      "Beryllium",
      "Boron",
      "Carbon",
      "Nitrogen",
      "Oxygen",
      "Fluorine",
      "Neon",
      "Sodium",
      "Magnesium",
      "Aluminium",
      "Silicon",
      "Phosphorus",
      "Sulfur",
      "Chlorine",
      "Argon",
      "Potassium",
      "Calcium",
      "Scandium",
      "Titanium",
      "Vanadium",
      "Chromium",
      "Manganese",
      "Iron",
      "Cobalt",
      "Nickel",
      "Copper",
      "Zinc",
      "Gallium",
      "Germanium",
      "Arsenic",
      "Selenium",
      "Bromine",
      "Krypton",
      "Rubidium",
      "Strontium",
      "Yttrium",
      "Zirconium",
      "Niobium",
      "Molybdenum",
      "Technetium",
      "Ruthenium",
      "Rhodium",
      "Palladium",
      "Silver",
      "Cadmium",
      "ndium",
      "Tin",
      "Antimony",
      "Tellurium",
      "odine",
      "Xenon",
      "Caesium",
      "Barium",
      "Lanthanum",
      "Cerium",
      "Praseodymiu",
      "Neodymium",
      "Promethium",
      "Samarium",
      "Europium",
      "Gadolinium",
      "Terbium",
      "Dysprosium",
      "Holmium",
      "Erbium",
      "Thulium",
      "Ytterbium",
      "Lutetium",
      "Hafnium",
      "Tantalum",
      "Tungsten",
      "Rhenium",
      "Osmium",
      "ridium",
      "Platinum",
      "Gold",
      "Mercury",
      "Thallium",
      "Lead",
      "Bismuth",
      "Polonium",
      "Astatine",
      "Radon",
      "Francium",
      "Radium",
      "Actinium",
      "Thorium",
      "Protactinium",
      "Uranium",
      "Neptunium",
      "Plutonium",
      "Americium",
      "Curium",
      "Berkelium",
      "Californium",
      "Einsteinium",
      "Fermium",
      "Mendelevium",
      "Nobelium",
      "Lawrencium",
      "Rutherfordium",
      "Dubnium",
      "Seaborgium",
      "Bohrium",
      "Hassium",
      "Meitnerium",
      "Darmstadtium",
      "Roentgenium",
      "Copernicium",
      "Ununtrium",
      "Flerovium",
      "Ununpentium",
      "Livermorium",
      "Ununseptium",
      "Ununoctium"
    ]
  },
  "colors": {
    "name": "Colors",
    "values": [
      "Amaranth",
      "Amber",
      "Amethyst",
      "Apricot",
      "Aquamarine",
      "Azure",
      "Baby blue",
      "Beige",
      "Black",
      "Blue",
      "Blue-green",
      "Blue-violet",
      "Blush",
      "Bronze",
      "Brown",
      "Burgundy",
      "Byzantium",
      "Carmine",
      "Cerise",
      "Cerulean",
      "Champagne",
      "Chartreuse green",
      "Chocolate",
      "Cobalt blue",
      "Coffee",
      "Copper",
      "Coral",
      "Crimson",
      "Cyan",
      "Desert sand",
      "Electric blue",
      "Emerald",
      "Erin",
      "Gold",
      "Gray",
      "Green",
      "Harlequin",
      "Indigo",
      "Ivory",
      "Jade",
      "Jungle green",
      "Lavender",
      "Lemon",
      "Lilac",
      "Lime",
      "Magenta",
      "Magenta rose",
      "Maroon",
      "Mauve",
      "Navy blue",
      "Ocher",
      "Olive",
      "Orange",
      "Orange-red",
      "Orchid",
      "Peach",
      "Pear",
      "Periwinkle",
      "Persian blue",
      "Pink",
      "Plum",
      "Prussian blue",
      "Puce",
      "Purple",
      "Raspberry",
      "Red",
      "Red-violet",
      "Rose",
      "Ruby",
      "Salmon",
      "Sangria",
      "Sapphire",
      "Scarlet",
      "Silver",
      "Slate gray",
      "Spring bud",
      "Spring green",
      "Tan",
      "Taupe",
      "Teal",
      "Turquoise",
      "Violet",
      "Viridian",
      "White",
      "Yellow"
    ]
  },
  "us_state_flowers": {
    "name": "US State Flowers",
    "values": [
      "Camellia",
      "Oak-leaf hydrangea",
      "Forget-me-not",
      "Saguaro cactus blossom",
      "Apple blossom",
      "California poppy",
      "Columbine",
      "Mountain laurel",
      "Peach blossom",
      "Orange blossom",
      "Tickseed",
      "Cherokee Rose",
      "Azalea",
      "Hawaiian hibiscus",
      "Syringa",
      "Mock Orange",
      "Violet",
      "Peony",
      "Wild Prairie Rose",
      "Sunflower",
      "Goldenrod",
      "Magnolia",
      "Louisiana Iris",
      "Black-eyed susan",
      "Mayflower",
      "Apple blossom",
      "Dwarf Lake Iris",
      "Magnolia",
      "Tickseed",
      "Hawthorn",
      "Bitterroot",
      "Goldenrod",
      "Sagebrush",
      "Purple lilac",
      "Violet",
      "Yucca flower",
      "Rose",
      "Flowering Dogwood",
      "Wild Prairie Rose",
      "Scarlet Carnation",
      "Large white trillium",
      "Oklahoma Rose",
      "Mistletoe",
      "Indian Blanket",
      "Oregon grape",
      "Mountain Laurel",
      "Penngift Crown Vetch",
      "Violet",
      "Yellow Jessamine",
      "Goldenrod",
      "Pasque flower",
      "Iris",
      "Purple Passionflower",
      "Bluebonnet",
      "Sego lily",
      "Red Clover",
      "American Dogwood",
      "Coast Rhododendron",
      "Rhododendron",
      "Wood Violet"
    ]
  },
  "common_asians_names": {
    "name": "Common Asian Names",
    "values": [
      "Lee",
      "Chen",
      "Wong",
      "Yang",
      "Wang",
      "Chang",
      "Chan",
      "Li",
      "Lin",
      "Liu",
      "Tan",
      "Lim",
      "Ng",
      "Ong",
      "Goh",
      "Chua",
      "Koh",
      "Teo",
      "Zhang",
      "Lam",
      "Leung",
      "Ho"
    ]
  }
};